### ISSUE TITLE
инициализация классов

### ISSUE THREAD

**Issue by DaRkLoL1** [n0sfer666/ui-kit__formElements#15]
классы нужно инициализировать в той же папке где они лежат, создать например файл dropdown-init.js 
import { Dropdown } from './Dropdown';
const arrDropdown = document.querySelectorAll('.js-dropdown');
arrDropdown.forEach((item, index) => {
  new Dropdown(item, index);
});

**Comment by DaRkLoL1** [comment]
У тебя немного не правильно нужно искать главные элементы по селектору класса и потом в цикле создавать обьекты и в классах использовать эти селекторы для поиска других селекторов, а то у тебя я вижу что ты ищешь из document и зачем ты передаешь в класс селектор страницы => 
![Скриншот 11-05-2020 16_57_50](https://user-images.githubusercontent.com/32780725/81570037-b8a79280-93a8-11ea-8846-91e0e9138647.png) компонент не должен быть зависим от страницы на которой он используется

**Comment by n0sfer666** [comment]
C инициализация pagination + apart возникли проблемы:
1) страница search-room загружалась около 10-15 сек (и это на моем i7 c 16gb RAM и локальным сервером);
2) при клонировании ноды, клонируется только DOM (без скриптов) и для pagination нужна повторная инициализация slick-carousel;

Единственное, на что хватило моего ума, вернуть таймаут (50мс) при инициализации класса Apart (возвращает быструю загрузку страницы search-room) и добавление в класс Pagination инициализацию класса (обеспечивает работу slick-carousel при перемещении между страницами модуля pagination)

**Comment by n0sfer666** [comment]
Сделал рефакторинг классов и их инициализации date-dropdown и booking, чтобы в карточке booking при вводе дат заезда и выезда происходил автоматический подсчёт стоимости (сначала первичной, а потом итоговой).

**Comment by Everrest1** [comment]
Можно закрыть

**Comment by n0sfer666** [comment]
Yes, sir
