### ISSUE TITLE
Классы

### ISSUE THREAD

**Issue by DaRkLoL1** [n0sfer666/ui-kit__formElements#17]
![Скриншот 11-05-2020 16_32_27](https://user-images.githubusercontent.com/32780725/81567475-08845a80-93a5-11ea-906a-9a1d41d9825b.png)
Сейчас каждый компонент написан функцией, которая в некоторых случаях(к примеру с dropdown.js) получается довольно громоздкой. Это всё лучше заменить на js-классы, чтобы потом уже для каждого найденного по селектору элемента создавать свой инстанс. Такой подход позволит разделить функционал по методам и сделать код более читаемым.

Также надобности в iife для ограничения видимости особо не будет, т.к. всё будет в пределах класса. Кстати вызов и создание инстансов надо сделать отдельно - рядом положить файл init.js, например. Чтобы если ты захотел этот класс импортировать и переиспользовать в другом компоненте тебе не пришлось бы убирать эти вызовы.

**Comment by DaRkLoL1** [comment]
![Скриншот 11-05-2020 16_33_23](https://user-images.githubusercontent.com/32780725/81567583-2e116400-93a5-11ea-8ecf-a8c97db281ed.png)
почему у тебя js код  в теге script в конце body не вызывается. Так не пришлось бы создавать событие для ready

**Comment by n0sfer666** [comment]
Создал класс Apart на замену функции setSlick

**Comment by n0sfer666** [comment]
Удалил скрипт main.js из head и поместил в конец body (на каждой странице)

**Comment by Everrest1** [comment]
Конструктор класса должен быть максимально легковесным
п.10. https://github.com/fullstack-development/front-end-best-practices/blob/master/JS/goodPractice.md

![image](https://user-images.githubusercontent.com/43137324/84468098-099ff480-ac8f-11ea-85e9-a6e134c952f5.png)

**Comment by Everrest1** [comment]
Это здесь зачем?

![image](https://user-images.githubusercontent.com/43137324/84468144-250aff80-ac8f-11ea-90b8-2ace20d5bfae.png)

**Comment by Everrest1** [comment]
Не понял задумки. Ты в методе создаёшь объекты, в которых объявляешь методы обработчики событий? Зачем `that`? Почему `let` везде? Надо рефакторить

![image](https://user-images.githubusercontent.com/43137324/84468375-b67a7180-ac8f-11ea-905e-eed51dfe13d5.png)

**Comment by n0sfer666** [comment]
> Конструктор класса должен быть максимально легковесным
> п.10. https://github.com/fullstack-development/front-end-best-practices/blob/master/JS/goodPractice.md
> 
> ![image](https://user-images.githubusercontent.com/43137324/84468098-099ff480-ac8f-11ea-85e9-a6e134c952f5.png)

Вынес код инициализации из конструктора в метод initiate() (3072f21)

**Comment by n0sfer666** [comment]
> Это здесь зачем?
> 
> ![image](https://user-images.githubusercontent.com/43137324/84468144-250aff80-ac8f-11ea-90b8-2ace20d5bfae.png)

Это поле хранит регулярное выражение для отделения разрядов числа (метод getStringWithSeparate(string)), игнорируя прочие символы (10000 $$$$$$ -> 10 000 $$$$$$)

**Comment by n0sfer666** [comment]
> Не понял задумки. Ты в методе создаёшь объекты, в которых объявляешь методы обработчики событий? Зачем `that`? Почему `let` везде? Надо рефакторить
> 
> ![image](https://user-images.githubusercontent.com/43137324/84468375-b67a7180-ac8f-11ea-905e-eed51dfe13d5.png)

let исправил на const везде кроме config (он не должен быть read-only). (e0690f9)
That нужен для того, чтобы объекты внутри метода видели поля класса (если убрать const that = this и заменить все that на this - конфигурация перестаёт выполнять необходимый функционал). Так работает JS.
Задумка исходит из сложности построения конфигурации для air-datepicker. Идея простая - есть 2 варианта использования datepicker'а - 2 отдельных поля и filter. В зависимости от значения isSingle (true | false), метод getConfig возвращает нужный вариант конфигурации (В filter date dropdown нет необходимости в onSelect). Не писать же два метода, которые почти полностью похожи друг на друга? :)

Итого: если нужно, чтобы прям "всё по красоте было", нужно писать модуль с нуля.

**Comment by Everrest1** [comment]
> > Это здесь зачем?
> > ![image](https://user-images.githubusercontent.com/43137324/84468144-250aff80-ac8f-11ea-90b8-2ace20d5bfae.png)
> 
> Это поле хранит регулярное выражение для отделения разрядов числа (метод getStringWithSeparate(string)), игнорируя прочие символы (10000 $$$$$$ -> 10 000 $$$$$$)

Тут имелось ввиду, что поля класса так не объявляются в js

**Comment by Everrest1** [comment]
> let исправил на const везде кроме config (он не должен быть read-only). 

Использование let в любом случае крайне не желательно

> That нужен для того, чтобы объекты внутри метода видели поля класса (если убрать const that = this и заменить все that на this - конфигурация перестаёт выполнять необходимый функционал). Так работает JS.

Для этого существует метод `bind()`

> Итого: если нужно, чтобы прям "всё по красоте было", нужно писать модуль с нуля.

Для этого и существует этот этап, научиться писать качественный, читаемый код

**Comment by Everrest1** [comment]
В любом случае обработчики событий выносятся в отдельные методы
п.11. https://github.com/fullstack-development/front-end-best-practices/blob/master/JS/goodPractice.md

**Comment by n0sfer666** [comment]
> > > Это здесь зачем?
> > > ![image](https://user-images.githubusercontent.com/43137324/84468144-250aff80-ac8f-11ea-90b8-2ace20d5bfae.png)
> > 
> > 
> > Это поле хранит регулярное выражение для отделения разрядов числа (метод getStringWithSeparate(string)), игнорируя прочие символы (10000 $$$$$$ -> 10 000 $$$$$$)
> 
> Тут имелось ввиду, что поля класса так не объявляются в js

Виноват... не понял. Так годится? (3b98271)

**Comment by n0sfer666** [comment]
Прошелся по всему проекту и вынес обработчики в отдельные методы (94c6ee7, 1417269, 30c832e).
Также исправил во всех js-файлах let на const, за исключением одного момента в dropdown (32ebb3e, 2927712). Ни одно из придуманных решений не сработало (dropdown.js, 70)

**Comment by Everrest1** [comment]
> > > > Это здесь зачем?
> > > > ![image](https://user-images.githubusercontent.com/43137324/84468144-250aff80-ac8f-11ea-90b8-2ace20d5bfae.png)
> > > 
> > > 
> > > Это поле хранит регулярное выражение для отделения разрядов числа (метод getStringWithSeparate(string)), игнорируя прочие символы (10000 $$$$$$ -> 10 000 $$$$$$)
> > 
> > 
> > Тут имелось ввиду, что поля класса так не объявляются в js
> 
> Виноват... не понял. Так годится? ([3b98271](https://github.com/n0sfer666/FSD-Task-2/commit/3b98271b1c14093511d96d5402c4924d1579fbb9))

А зачем `static`? Он используется вне класса? Вынеси тогда, как утилиту. Но лучше сделать обычной переменной или обычным полем

**Comment by n0sfer666** [comment]
Исправил в другом ишью (7ed118f) Виноват... Тупанул=\

**Comment by Everrest1** [comment]
Можно закрыть

**Comment by n0sfer666** [comment]
ok, boss
