### ISSUE TITLE
Переполнение 

### ISSUE THREAD

**Issue by DaRkLoL1** [n0sfer666/ui-kit__formElements#18]
![Скриншот 11-05-2020 16_37_10](https://user-images.githubusercontent.com/32780725/81568297-3e760e80-93a6-11ea-8bab-62ae210dc009.png)
![Скриншот 11-05-2020 16_41_39](https://user-images.githubusercontent.com/32780725/81568366-551c6580-93a6-11ea-9396-2ae1bcda2670.png)
Посмотри по всему проекту прост вставляй текст везде)

**Comment by n0sfer666** [comment]
Сделано.

**Comment by Everrest1** [comment]
Думаю, можно закрыть

**Comment by n0sfer666** [comment]
Yes, sir :)
