### ISSUE TITLE
Perfect Pixel

### ISSUE THREAD

**Issue by DaRkLoL1** [n0sfer666/ui-kit__formElements#19]
Выложи плиз изображения страниц,  по которым подгонялся PerfectPixel, и скрин с его настройками ->
![Скриншот 11-05-2020 17_12_51](https://user-images.githubusercontent.com/32780725/81571472-ab8ba300-93aa-11ea-81f3-9941d3d6f492.png)

**Comment by n0sfer666** [comment]
![image](https://user-images.githubusercontent.com/21785370/83945759-7ccfe380-a815-11ea-96ce-70fcf0071e5e.png)
настройки везде одинаковые

**Comment by n0sfer666** [comment]
шаблон для Colors&Types
![Colors   Type](https://user-images.githubusercontent.com/21785370/83977895-6e182800-a90c-11ea-9c1a-22cfca5c9ce5.png)

**Comment by n0sfer666** [comment]
шаблон Form Elements
!Важно! Для проверки нужно кликнуть на expandable-checkbox-list и 3 dropdown'а в середине страницы.
![Form Elements](https://user-images.githubusercontent.com/21785370/83978265-e849ac00-a90e-11ea-9357-dda6ba23eb5a.png)

**Comment by n0sfer666** [comment]
Шаблон Cards.
Не смог добавить кнопки (очистить, применить) для air-datepicker в inline (onShow игнорируется).
![Cards](https://user-images.githubusercontent.com/21785370/84055510-99a71b00-a9bd-11ea-8a2c-3ed17de6d979.png)

**Comment by n0sfer666** [comment]
Шаблон Headers & Footers
![Headers   Footers](https://user-images.githubusercontent.com/21785370/84067582-3d99c200-a9d0-11ea-997a-846a54700a30.png)

**Comment by n0sfer666** [comment]
Шаблон Landing Page.
![Landing page](https://user-images.githubusercontent.com/21785370/84068563-d0872c00-a9d1-11ea-82a1-510d9cb5c6c6.png)

**Comment by n0sfer666** [comment]
Шаблон Registration
![Registration](https://user-images.githubusercontent.com/21785370/84170776-accfee80-aa82-11ea-82e9-e141db3a7937.jpg)

**Comment by n0sfer666** [comment]
Шаблон Sign in
![Sign in](https://user-images.githubusercontent.com/21785370/84170848-c2ddaf00-aa82-11ea-8b20-a263f270ddd8.png)

**Comment by n0sfer666** [comment]
Шаблон Room Details
![Room details](https://user-images.githubusercontent.com/21785370/84173798-6ed4c980-aa86-11ea-9b1e-2430885d6cd6.jpg)

**Comment by n0sfer666** [comment]
Шаблон Search room. Filter
![Search-room  Filter](https://user-images.githubusercontent.com/21785370/84179688-03432a00-aa8f-11ea-9bc7-d6f269bdf453.jpg)

**Comment by Everrest1** [comment]
Можно закрыть

**Comment by n0sfer666** [comment]
yes, sir
