### ISSUE TITLE
Линтер

### ISSUE THREAD

**Issue by Everrest1** [n0sfer666/ui-kit__formElements#21]
В проекте вроде подключен eslint, но его правила почти везде проигнорированы.

**Comment by Everrest1** [comment]
Линтер всё-ещё подсвечивает ошибки в проекте
![image](https://user-images.githubusercontent.com/43137324/86086438-d349de00-bab2-11ea-8221-c38361a84c52.png)

**Comment by n0sfer666** [comment]
В range-slider'e не исправлена одна ошибка:
![image](https://user-images.githubusercontent.com/21785370/86362211-98e06c80-bc7d-11ea-8682-ab07421c24d6.png)
Причина: особенности конфигурации модуля.

**Comment by n0sfer666** [comment]
Все ошибки кроме одной (описана вышел) исправлены.

**Comment by Everrest1** [comment]
> В range-slider'e не исправлена одна ошибка:
> ![image](https://user-images.githubusercontent.com/21785370/86362211-98e06c80-bc7d-11ea-8682-ab07421c24d6.png)
> Причина: особенности конфигурации модуля.

Просто нужно вынести обработчик события в отдельный метод
По стандартам п.11 https://github.com/fullstack-development/front-end-best-practices/blob/master/JS/goodPractice.md

**Comment by n0sfer666** [comment]
> > В range-slider'e не исправлена одна ошибка:
> > ![image](https://user-images.githubusercontent.com/21785370/86362211-98e06c80-bc7d-11ea-8682-ab07421c24d6.png)
> > Причина: особенности конфигурации модуля.
> 
> Просто нужно вынести обработчик события в отдельный метод
> По стандартам п.11 https://github.com/fullstack-development/front-end-best-practices/blob/master/JS/goodPractice.md

Исправил. 1000 извинений, я откуда-то придумал, что функции с параметрами отличными от event не работают в конструкции addListener('click', this.method) =\ По-этому в первый раз не исправил. (618550c)
