### ISSUE TITLE
Стили в js

### ISSUE THREAD

**Issue by Everrest1** [n0sfer666/ui-kit__formElements#22]
По стандартам через js стили менять нельзя п.22 https://github.com/fullstack-development/front-end-best-practices/blob/master/JS/goodPractice.md

![image](https://user-images.githubusercontent.com/43137324/84859929-25d0d680-b07f-11ea-953b-e4f5d0676a13.png)

**Comment by n0sfer666** [comment]
Исправил + посмотрел по всему проекту (больше нигде не встречается) (d97f0d6)
