### ISSUE TITLE
Классы блоков

### ISSUE THREAD

**Issue by Everrest1** [n0sfer666/ui-kit__formElements#23]
Почему то у элементов сразу по два разных класса

![image](https://user-images.githubusercontent.com/43137324/84860709-99bfae80-b080-11ea-9e23-be00be5ccd1e.png)

![image](https://user-images.githubusercontent.com/43137324/84861172-806b3200-b081-11ea-9516-8625071e050f.png)

**Comment by Everrest1** [comment]
Нельзя нарушать инкапсуляцию блока. Никто кроме самого блока не должен знать детали его реализации. К тому же класс `js-undefined-button` невалидный
![image](https://user-images.githubusercontent.com/43137324/84860868-e86d4880-b080-11ea-9a04-237f401e20c3.png)

**Comment by Everrest1** [comment]
Тоже.
Во-первых, непонятно какие значения я могу сюда передать.
Во-вторых, эти значения произвольные, а значит, я могу поместить туда невалидное значение

![image](https://user-images.githubusercontent.com/43137324/84860999-2ec2a780-b081-11ea-945a-0e3be7689aab.png)

**Comment by n0sfer666** [comment]
> Почему то у элементов сразу по два разных класса
> 
> ![image](https://user-images.githubusercontent.com/43137324/84860709-99bfae80-b080-11ea-9e23-be00be5ccd1e.png)
> 
> ![image](https://user-images.githubusercontent.com/43137324/84861172-806b3200-b081-11ea-9516-8625071e050f.png)

Первый селектор используется для стилизация (по-этому, он одинаковый на первом и втором скриншоте), а второй с приставкой js- для поиска по DOM (п.1 - https://github.com/fullstack-development/front-end-best-practices/blob/master/JS/jQuery.md)

**Comment by n0sfer666** [comment]
> Нельзя нарушать инкапсуляцию блока. Никто кроме самого блока не должен знать детали его реализации. К тому же класс `js-undefined-button` невалидный
> ![image](https://user-images.githubusercontent.com/43137324/84860868-e86d4880-b080-11ea-9a04-237f401e20c3.png)

Удалил у всех элементов параметр jsClass, добавил компонент masked-text-field (59c2f1b)

**Comment by n0sfer666** [comment]
Также разбил компонент button на button-action, button-border, button-gradient и button-text (+отрефакторил связанные компоненты) (b0872ad)
Отрефакторил кнопки в date-dropdown'е (6a63c00)

**Comment by n0sfer666** [comment]
> Тоже.
> Во-первых, непонятно какие значения я могу сюда передать.
> Во-вторых, эти значения произвольные, а значит, я могу поместить туда невалидное значение
> 
> ![image](https://user-images.githubusercontent.com/43137324/84860999-2ec2a780-b081-11ea-945a-0e3be7689aab.png)

Добавил switch-case по аналогии с type-block. Надеюсь, так норм (3168b89)

**Comment by Everrest1** [comment]
> > Почему то у элементов сразу по два разных класса
> > ![image](https://user-images.githubusercontent.com/43137324/84860709-99bfae80-b080-11ea-9e23-be00be5ccd1e.png)
> > ![image](https://user-images.githubusercontent.com/43137324/84861172-806b3200-b081-11ea-9516-8625071e050f.png)
> 
> Первый селектор используется для стилизация (по-этому, он одинаковый на первом и втором скриншоте), а второй с приставкой js- для поиска по DOM (п.1 - https://github.com/fullstack-development/front-end-best-practices/blob/master/JS/jQuery.md)

Да, только вот они не должны отличаться. У тебя один элемент имеет два имени. Если у тебя есть имя у эелемента date-dropdown__filter, то для селекта через js может быть только js-date-dropdown__filter и никак иначе

**Comment by Everrest1** [comment]
> > Тоже.
> > Во-первых, непонятно какие значения я могу сюда передать.
> > Во-вторых, эти значения произвольные, а значит, я могу поместить туда невалидное значение
> > ![image](https://user-images.githubusercontent.com/43137324/84860999-2ec2a780-b081-11ea-945a-0e3be7689aab.png)
> 
> Добавил switch-case по аналогии с type-block. Надеюсь, так норм ([3168b89](https://github.com/n0sfer666/FSD-Task-2/commit/3168b89991a42d429c1d2ea83e632ed0c2dc2fa0))

Излишнее дублирование получилось, у тебя меняется только класс модификатора, вот его только можно поместить в переменную

**Comment by Everrest1** [comment]
> Также разбил компонент button на button-action, button-border, button-gradient и button-text (+отрефакторил связанные компоненты) ([b0872ad](https://github.com/n0sfer666/FSD-Task-2/commit/b0872ad5a554c5aa5f23aacad20862fe671fd20c))
> Отрефакторил кнопки в date-dropdown'е ([6a63c00](https://github.com/n0sfer666/FSD-Task-2/commit/6a63c00c847be209c1e8c771311655245ae980ea))

Не, так делать не надо. У тебя теперь 4 блока, имеющих схожую структуру, и что плохо одни и те же классы. Лучше сделать один блок button, параметром указывать тип кнопки, и уже работать модификаторами

**Comment by n0sfer666** [comment]
> > > Тоже.
> > > Во-первых, непонятно какие значения я могу сюда передать.
> > > Во-вторых, эти значения произвольные, а значит, я могу поместить туда невалидное значение
> > > ![image](https://user-images.githubusercontent.com/43137324/84860999-2ec2a780-b081-11ea-945a-0e3be7689aab.png)
> > 
> > 
> > Добавил switch-case по аналогии с type-block. Надеюсь, так норм ([3168b89](https://github.com/n0sfer666/FSD-Task-2/commit/3168b89991a42d429c1d2ea83e632ed0c2dc2fa0))
> 
> Излишнее дублирование получилось, у тебя меняется только класс модификатора, вот его только можно поместить в переменную

Исправил (6db8623)



> > Также разбил компонент button на button-action, button-border, button-gradient и button-text (+отрефакторил связанные компоненты) ([b0872ad](https://github.com/n0sfer666/FSD-Task-2/commit/b0872ad5a554c5aa5f23aacad20862fe671fd20c))
> > Отрефакторил кнопки в date-dropdown'е ([6a63c00](https://github.com/n0sfer666/FSD-Task-2/commit/6a63c00c847be209c1e8c771311655245ae980ea))
> 
> Не, так делать не надо. У тебя теперь 4 блока, имеющих схожую структуру, и что плохо одни и те же классы. Лучше сделать один блок button, параметром указывать тип кнопки, и уже работать модификаторами

Исправил (7dfcea3)

**Comment by Everrest1** [comment]
Пройдись по всему проекту, ещё много где осталось

![image](https://user-images.githubusercontent.com/43137324/86089980-4c98ff00-baba-11ea-82b4-7f8f7f3fc58d.png)

**Comment by Everrest1** [comment]
В этом случае, необходимо ещё добавить класс без приставки `js-`

![image](https://user-images.githubusercontent.com/43137324/86090048-6afefa80-baba-11ea-9b7d-6354a29f89cf.png)

**Comment by n0sfer666** [comment]
> Пройдись по всему проекту, ещё много где осталось
> 
> ![image](https://user-images.githubusercontent.com/43137324/86089980-4c98ff00-baba-11ea-82b4-7f8f7f3fc58d.png)



> В этом случае, необходимо ещё добавить класс без приставки `js-`
> 
> ![image](https://user-images.githubusercontent.com/43137324/86090048-6afefa80-baba-11ea-9b7d-6354a29f89cf.png)

Исправил (8032336)

**Comment by Everrest1** [comment]
Всё-ещё нахожу элементы с разными классами. 
Получается, что если смотреть только в стилях у нас один есть один элемент, если смотреть только в js, то у нас это совсем другой элемент, и у меня будет складываться ложное представление о структуре блока. т.к. я уверен, что здесь два разных элемента, хотя это один на самом деле.
Пройдись по всему проекту, плиз

![image](https://user-images.githubusercontent.com/43137324/86431826-e05f0b00-bd06-11ea-9d8b-cc4587ffb16b.png)
![image](https://user-images.githubusercontent.com/43137324/86431837-e81eaf80-bd06-11ea-9664-926e11009f59.png)

**Comment by n0sfer666** [comment]
> Всё-ещё нахожу элементы с разными классами.
> Получается, что если смотреть только в стилях у нас один есть один элемент, если смотреть только в js, то у нас это совсем другой элемент, и у меня будет складываться ложное представление о структуре блока. т.к. я уверен, что здесь два разных элемента, хотя это один на самом деле.
> Пройдись по всему проекту, плиз
> 
> ![image](https://user-images.githubusercontent.com/43137324/86431826-e05f0b00-bd06-11ea-9d8b-cc4587ffb16b.png)

Исправил (cd17a56)
> ![image](https://user-images.githubusercontent.com/43137324/86431837-e81eaf80-bd06-11ea-9664-926e11009f59.png)

Исправил (37abfd9)

Остальное исправил до этого.
