### ISSUE TITLE
Приведение типов

### ISSUE THREAD

**Issue by Everrest1** [n0sfer666/ui-kit__formElements#24]
По стайлгайду AirBnb нельзя переопределять значение параметров функции. 
Довольно странный код. Эта проверка сейчас ничего не делает. Если в переменной `string` (название не очень) будет лежать, например, undefined, то функция вернёт невалидное значение
![image](https://user-images.githubusercontent.com/43137324/85827073-85716500-b796-11ea-870e-96a0d2a53a0d.png)

**Comment by Everrest1** [comment]
Здесь, если в параметр придёт не число, то в `daysIn` будет лежать `NaN`
![image](https://user-images.githubusercontent.com/43137324/85827671-c8800800-b797-11ea-9b26-faffaeb60e38.png)

**Comment by Everrest1** [comment]
Если это число, то так преобразовывать в строку необязательно 

![image](https://user-images.githubusercontent.com/43137324/85827856-244a9100-b798-11ea-81e8-9f750eb108e3.png)

**Comment by n0sfer666** [comment]
> По стайлгайду AirBnb нельзя переопределять значение параметров функции.
> Довольно странный код. Эта проверка сейчас ничего не делает. Если в переменной `string` (название не очень) будет лежать, например, undefined, то функция вернёт невалидное значение
> ![image](https://user-images.githubusercontent.com/43137324/85827073-85716500-b796-11ea-870e-96a0d2a53a0d.png)



> Здесь, если в параметр придёт не число, то в `daysIn` будет лежать `NaN`
> ![image](https://user-images.githubusercontent.com/43137324/85827671-c8800800-b797-11ea-9b26-faffaeb60e38.png)



> Если это число, то так преобразовывать в строку необязательно
> 
> ![image](https://user-images.githubusercontent.com/43137324/85827856-244a9100-b798-11ea-81e8-9f750eb108e3.png)

Исправил

**Comment by Everrest1** [comment]
А теперь, если в `string` будет объект, то получится что-то вроде такой строки `[object object].

![image](https://user-images.githubusercontent.com/43137324/86089493-65ed7b80-bab9-11ea-9785-c356781f3636.png)

Не нужно делать такое нагромождение в условии, не нужно делать дополнительного приведения, если хочешь сделать проверку на тип, думаю достаточно будет проверить на валидный тип, если нет, то не делать вычислений и вывести заглушку с ошибкой

**Comment by n0sfer666** [comment]
Убрал проверку в getStringWithSeparate (f5dd85e)
