### ISSUE TITLE
Обработчики событий

### ISSUE THREAD

**Issue by Everrest1** [n0sfer666/ui-kit__formElements#25]
> 11. Выносить обработчики событий в отдельные функции

https://github.com/fullstack-development/front-end-best-practices/blob/master/JS/goodPractice.md

**Comment by n0sfer666** [comment]
Сделано (использовал eslint-plugin-fsd), за исключением одного [места](https://github.com/n0sfer666/FSD-Task-2/issues/21#issuecomment-652993371)

**Comment by Everrest1** [comment]
> Сделано (использовал eslint-plugin-fsd), за исключением одного [места](https://github.com/n0sfer666/FSD-Task-2/issues/21#issuecomment-652993371)

А почему? Что мешает так сделать?

**Comment by Everrest1** [comment]
Методы обработчики событий должны именоваться по шаблону `handleElementNameEventName`

**Comment by Everrest1** [comment]
Здесь можно без стрелочной функции

![image](https://user-images.githubusercontent.com/43137324/86432573-3f258400-bd09-11ea-875f-55a383bccbd2.png)

**Comment by n0sfer666** [comment]
> Методы обработчики событий должны именоваться по шаблону `handleElementNameEventName`

Переименовал (1b4707d)

> > Сделано (использовал eslint-plugin-fsd), за исключением одного [места](https://github.com/n0sfer666/FSD-Task-2/issues/21#issuecomment-652993371)
> 
> А почему? Что мешает так сделать?

Некомпетентность :) Исправил (618550c)

**Comment by n0sfer666** [comment]
> Здесь можно без стрелочной функции
> 
> ![image](https://user-images.githubusercontent.com/43137324/86432573-3f258400-bd09-11ea-875f-55a383bccbd2.png)

Исправил (f4358e6)
UPD. Не работало... исправил (2f3550e)

**Comment by Everrest1** [comment]
Здесь тоже нужно поменять название метода

![image](https://user-images.githubusercontent.com/43137324/87119005-df415700-c28d-11ea-98bb-5d2182452da1.png)

**Comment by Everrest1** [comment]
![image](https://user-images.githubusercontent.com/43137324/87119064-fe3fe900-c28d-11ea-83cb-853fde6c729a.png)

**Comment by Everrest1** [comment]
По стандартам п.5 https://github.com/fullstack-development/front-end-best-practices/blob/master/JS/jQuery.md

По стандартам п.11 https://github.com/fullstack-development/front-end-best-practices/blob/master/JS/goodPractice.md

![image](https://user-images.githubusercontent.com/43137324/87119415-f5034c00-c28e-11ea-84e9-e304d2dd798c.png)

**Comment by n0sfer666** [comment]
> Здесь тоже нужно поменять название метода
> 
> ![image](https://user-images.githubusercontent.com/43137324/87119005-df415700-c28d-11ea-98bb-5d2182452da1.png)
> ![image](https://user-images.githubusercontent.com/43137324/87119064-fe3fe900-c28d-11ea-83cb-853fde6c729a.png)
Исправил в issue #27 (a13f516) + нашел еще в двух компонентах ту же ошибку.

**Comment by n0sfer666** [comment]
> По стандартам п.5 https://github.com/fullstack-development/front-end-best-practices/blob/master/JS/jQuery.md
> 
> По стандартам п.11 https://github.com/fullstack-development/front-end-best-practices/blob/master/JS/goodPractice.md
> 
> ![image](https://user-images.githubusercontent.com/43137324/87119415-f5034c00-c28e-11ea-84e9-e304d2dd798c.png)

Исправил (caa7fa4)

**Comment by Everrest1** [comment]
Результат `bind` сохраняется не в отдельную локальную переменную, а переопределяется поле класса. Так ты не сохраняешь инстанс функции и не сможешь в случае необходимости отвязать событие без доступа к этой переменной.

Есть устоявшаяся конструкция `this.handleInctanceClick = this.handleInctanceClick.bind(this);`

![image](https://user-images.githubusercontent.com/43137324/87504059-c9a9a400-c676-11ea-9e87-df666a457166.png)

**Comment by n0sfer666** [comment]
> Результат `bind` сохраняется не в отдельную локальную переменную, а переопределяется поле класса. Так ты не сохраняешь инстанс функции и не сможешь в случае необходимости отвязать событие без доступа к этой переменной.
> 
> Есть устоявшаяся конструкция `this.handleInctanceClick = this.handleInctanceClick.bind(this);`
> 
> ![image](https://user-images.githubusercontent.com/43137324/87504059-c9a9a400-c676-11ea-9e87-df666a457166.png)

Исправил в 6ти компонентах (100dd9c).
Создал отдельный метод bindContext().
В date-dropdown 2 метода bindContext() и bindDpContext(). (b914f9e)

**Comment by Everrest1** [comment]
Тернарник - это выражение, его можно поместить где определяешь свойство объекту. 

![image](https://user-images.githubusercontent.com/43137324/87878326-99566280-c9f4-11ea-9700-cd8944bd0407.png)

**Comment by n0sfer666** [comment]
> Тернарник - это выражение, его можно поместить где определяешь свойство объекту.
> 
> ![image](https://user-images.githubusercontent.com/43137324/87878326-99566280-c9f4-11ea-9700-cd8944bd0407.png)

Сделал в #26 ( (b7ad175)

**Comment by Everrest1** [comment]
Даже если это аргумент функции, всё равно должно быть понятно, что это обработчик, который мы вешаем на событие

![image](https://user-images.githubusercontent.com/43137324/96545800-20e49380-12ba-11eb-8a65-89ed545fa0b1.png)

**Comment by n0sfer666** [comment]
> Даже если это аргумент функции, всё равно должно быть понятно, что это обработчик, который мы вешаем на событие
> 
> ![image](https://user-images.githubusercontent.com/43137324/96545800-20e49380-12ba-11eb-8a65-89ed545fa0b1.png)

Исправил (3c3d3f1)

**Comment by Everrest1** [comment]
Не, `onClick` верни обратно) Я имел ввиду `callback`

![image](https://user-images.githubusercontent.com/43137324/97392260-c58a5500-18fa-11eb-9f45-f99aa23467f3.png)

**Comment by n0sfer666** [comment]
handleClick годится?
