### ISSUE TITLE
Структура кода js

### ISSUE THREAD

**Issue by Everrest1** [n0sfer666/ui-kit__formElements#26]
Хорошей практикой является разбиение кода на функции по принципу единой ответственности.
Когда однозначно можно сказать, что эта функция выполняет.

По стандартам П.6
https://github.com/fullstack-development/front-end-best-practices/blob/master/JS/jQuery.md

Вынеси поиск и сохранение элементов DOM в отдельную функцию

![image](https://user-images.githubusercontent.com/43137324/86087316-f9707d80-bab4-11ea-9bd6-1c96affb524b.png)

**Comment by Everrest1** [comment]
Во всём проекте

![image](https://user-images.githubusercontent.com/43137324/86087370-1d33c380-bab5-11ea-998f-3971849c6612.png)

**Comment by Everrest1** [comment]
Я имел ввиду вынести в отдельный метод, поиск по DOM-документу. Получился бы метод, который только сохраняет ссылки на элементы и ничего больше не делает. И, например, метод, который навешивает обработчики событий на элементы, и не занимается ни поиском, ни вычислениями, ни чем либо ещё.

Метод `getValueOfElement` выглядит странно. Откуда нам знать, что лежит в 0 индексе, и почему именно 0 индекс
![image](https://user-images.githubusercontent.com/43137324/86432747-de4a7b80-bd09-11ea-9a4d-a156cca1042c.png)

**Comment by Everrest1** [comment]
Зачем понадобилось обращаться к `constructor`? Не нужно так

![image](https://user-images.githubusercontent.com/43137324/86433112-ddfeb000-bd0a-11ea-90b8-6e726c139d34.png)

**Comment by Everrest1** [comment]
Если решил собрать все элементы в один объект, хотя это совсем необязательно, то стоит использовать деструктуризацию

![image](https://user-images.githubusercontent.com/43137324/86433217-2b7b1d00-bd0b-11ea-8ec1-fa7929014703.png)

**Comment by n0sfer666** [comment]
> Я имел ввиду вынести в отдельный метод, поиск по DOM-документу. Получился бы метод, который только сохраняет ссылки на элементы и ничего больше не делает. И, например, метод, который навешивает обработчики событий на элементы, и не занимается ни поиском, ни вычислениями, ни чем либо ещё.
> 
> Метод `getValueOfElement` выглядит странно. Откуда нам знать, что лежит в 0 индексе, и почему именно 0 индекс
> ![image](https://user-images.githubusercontent.com/43137324/86432747-de4a7b80-bd09-11ea-9a4d-a156cca1042c.png)



> Зачем понадобилось обращаться к `constructor`? Не нужно так
> 
> ![image](https://user-images.githubusercontent.com/43137324/86433112-ddfeb000-bd0a-11ea-90b8-6e726c139d34.png)

Исправил (d807c52)



> Если решил собрать все элементы в один объект, хотя это совсем необязательно, то стоит использовать деструктуризацию
> 
> ![image](https://user-images.githubusercontent.com/43137324/86433217-2b7b1d00-bd0b-11ea-8ec1-fa7929014703.png)

Сделано (9e2b930)

**Comment by Everrest1** [comment]
Вынеси поиск элементов в отдельный метод getHTMLElements

![image](https://user-images.githubusercontent.com/43137324/87118714-1feca080-c28d-11ea-9242-a0234e666b6b.png)

**Comment by Everrest1** [comment]
`bind` для обработчиков обычно выполняется в конструкторе или отдельном методе

![image](https://user-images.githubusercontent.com/43137324/87118884-8ffb2680-c28d-11ea-98e2-8c98f11bab27.png)

**Comment by Everrest1** [comment]
По стандартам п.10 https://github.com/fullstack-development/front-end-best-practices/blob/master/JS/goodPractice.md

![image](https://user-images.githubusercontent.com/43137324/87119260-8aeaa700-c28e-11ea-9ddf-8af42b457296.png)

**Comment by n0sfer666** [comment]
> Вынеси поиск элементов в отдельный метод getHTMLElements
> 
> ![image](https://user-images.githubusercontent.com/43137324/87118714-1feca080-c28d-11ea-9242-a0234e666b6b.png)

Сделал (2a64b04 aa7ff32)

**Comment by n0sfer666** [comment]
> По стандартам п.10 https://github.com/fullstack-development/front-end-best-practices/blob/master/JS/goodPractice.md
> 
> ![image](https://user-images.githubusercontent.com/43137324/87119260-8aeaa700-c28e-11ea-9ddf-8af42b457296.png)

Исправил (341d182)

**Comment by Hahahayabanan** [comment]
Результат `bind` сохраняется не в отдельную локальную переменную, а переопределяется поле класса. Так ты не сохраняешь инстанс функции и не сможешь в случае необходимости отвязать событие без доступа к этой переменной.

Есть устоявшаяся конструкция `this.handleInctanceClick = this.handleInctanceClick.bind(this);`

![image](https://user-images.githubusercontent.com/43137324/87504059-c9a9a400-c676-11ea-9e87-df666a457166.png)

**Comment by Everrest1** [comment]
Неиспользуемые переменные

![image](https://user-images.githubusercontent.com/43137324/87878805-ade82a00-c9f7-11ea-8e20-dd443da01dec.png)
![image](https://user-images.githubusercontent.com/43137324/87878809-b7719200-c9f7-11ea-83ad-d46213309b42.png)
![image](https://user-images.githubusercontent.com/43137324/87878812-bf313680-c9f7-11ea-909e-a26998cff454.png)

**Comment by Everrest1** [comment]
Тоже вынеси из конструктора в отдельный метод

![image](https://user-images.githubusercontent.com/43137324/87878854-fb649700-c9f7-11ea-8c45-a12e262fc961.png)

**Comment by Everrest1** [comment]
![image](https://user-images.githubusercontent.com/43137324/87878863-08818600-c9f8-11ea-99e1-3cdda6657a83.png)

**Comment by Everrest1** [comment]
Лучше вынести из конструктора всё лишнее

![image](https://user-images.githubusercontent.com/43137324/87878976-d290d180-c9f8-11ea-9a86-12d5ba08e195.png)

**Comment by n0sfer666** [comment]
> Неиспользуемые переменные
> 
> ![image](https://user-images.githubusercontent.com/43137324/87878805-ade82a00-c9f7-11ea-8e20-dd443da01dec.png)
> ![image](https://user-images.githubusercontent.com/43137324/87878809-b7719200-c9f7-11ea-83ad-d46213309b42.png)
> ![image](https://user-images.githubusercontent.com/43137324/87878812-bf313680-c9f7-11ea-909e-a26998cff454.png)

Удалил (b7ad175)

**Comment by n0sfer666** [comment]
> Тоже вынеси из конструктора в отдельный метод
> 
> ![image](https://user-images.githubusercontent.com/43137324/87878854-fb649700-c9f7-11ea-8c45-a12e262fc961.png)

Вынес в метод initIncstanceElements (b1b85dc)

**Comment by n0sfer666** [comment]
![image](https://user-images.githubusercontent.com/43137324/87878863-08818600-c9f8-11ea-99e1-3cdda6657a83.png)

Вынес в метод initIncstanceElements (15ea0c1)

**Comment by n0sfer666** [comment]
> > Тоже вынеси из конструктора в отдельный метод
> > ![image](https://user-images.githubusercontent.com/43137324/87878854-fb649700-c9f7-11ea-8c45-a12e262fc961.png)
> 
> Вынес в метод initIncstanceElements ([b1b85dc](https://github.com/n0sfer666/FSD-Task-2/commit/b1b85dc6c26107351f5502505ebf30f6963d3c62))

Вынес и разделил на 2 метода initInstanceElements и initInstanceVars (dea67f8)

**Comment by n0sfer666** [comment]
Сделал по аналогии DateDropdown (a250493), Apart, Dropdown, MaskedTextField, Pagination (9a1dd2f)
