### ISSUE TITLE
Дублирование кода

### ISSUE THREAD

**Issue by Everrest1** [n0sfer666/ui-kit__formElements#27]
Здесь можно избежать дублирования кода

![image](https://user-images.githubusercontent.com/43137324/86431204-329f2c80-bd05-11ea-82bb-7861ef3e8f0c.png)
![image](https://user-images.githubusercontent.com/43137324/86431213-3b8ffe00-bd05-11ea-959e-69fa58472f3e.png)
![image](https://user-images.githubusercontent.com/43137324/86431225-4480cf80-bd05-11ea-8637-8db0dd568f9e.png)

**Comment by n0sfer666** [comment]
Исправил. (Шаблон с чекбоксом (2ой скриншот) нашел еще в 4х компонентах)

**Comment by Everrest1** [comment]
Здесь лучше сразу возвращать литерал

![image](https://user-images.githubusercontent.com/43137324/87118949-ba4ce400-c28d-11ea-83e5-683c592c7af8.png)

**Comment by Everrest1** [comment]
Интересное решение, но надо рефаторить классы, сейчас они не соответствуют требованиям БЭМ

![image](https://user-images.githubusercontent.com/43137324/87119698-bfab2e00-c28f-11ea-8160-57ad1fb0a86b.png)

**Comment by n0sfer666** [comment]
> Здесь лучше сразу возвращать литерал
> 
> ![image](https://user-images.githubusercontent.com/43137324/87118949-ba4ce400-c28d-11ea-83e5-683c592c7af8.png)

Исправил (нашел еще в 2х компонентах) (a13f516)

**Comment by n0sfer666** [comment]
> Интересное решение, но надо рефаторить классы, сейчас они не соответствуют требованиям БЭМ
> 
> ![image](https://user-images.githubusercontent.com/43137324/87119698-bfab2e00-c28f-11ea-8160-57ad1fb0a86b.png)



Исправил в другом issue #9 (65fb964)

**Comment by Everrest1** [comment]
Не, сейчас у тебя получается структура такого формата `'button button_text button_text_active'`.
Во-первых, имя модификатора должно быть прилагательным.
Во-вторых, `button_text_active` это вид модификатора ключ-значение, что неверно. Сделай булевый модификатор для состояния, к примеру `button_active`.

![image](https://user-images.githubusercontent.com/43137324/87502860-d1b41480-c673-11ea-871f-0a4189e74868.png)

**Comment by n0sfer666** [comment]
> Не, сейчас у тебя получается структура такого формата `'button button_text button_text_active'`.
> Во-первых, имя модификатора должно быть прилагательным.
> Во-вторых, `button_text_active` это вид модификатора ключ-значение, что неверно. Сделай булевый модификатор для состояния, к примеру `button_active`.
> 
> ![image](https://user-images.githubusercontent.com/43137324/87502860-d1b41480-c673-11ea-871f-0a4189e74868.png)

Исправил. В коммитах указал #9 (ab9b7b2, 20f1e70)

**Comment by Everrest1** [comment]
Дублирование)

![image](https://user-images.githubusercontent.com/43137324/87878652-b1c77c80-c9f6-11ea-86ba-bd353a3123a4.png)

**Comment by Everrest1** [comment]
В проекте очень часто используются одни и теже заголовки. Стоит сделать отдельный блок

![image](https://user-images.githubusercontent.com/43137324/87878742-40d49480-c9f7-11ea-958f-1a648e251f6c.png)

**Comment by n0sfer666** [comment]
> Дублирование)
> 
> ![image](https://user-images.githubusercontent.com/43137324/87878652-b1c77c80-c9f6-11ea-86ba-bd353a3123a4.png)

Исправил (c07127b)

**Comment by n0sfer666** [comment]
> В проекте очень часто используются одни и теже заголовки. Стоит сделать отдельный блок
> 
> ![image](https://user-images.githubusercontent.com/43137324/87878742-40d49480-c9f7-11ea-958f-1a648e251f6c.png)

Создал новые компоненты и отрефакторил весь проект (c2c67f2, b0b5c3a, 278fdb0).
Закралась крамольная мысль, что необходимо было сделать другое, но пока оставлю так...

**Comment by Everrest1** [comment]
> > В проекте очень часто используются одни и теже заголовки. Стоит сделать отдельный блок
> > ![image](https://user-images.githubusercontent.com/43137324/87878742-40d49480-c9f7-11ea-958f-1a648e251f6c.png)
> 
> Создал новые компоненты и отрефакторил весь проект ([c2c67f2](https://github.com/n0sfer666/FSD-Task-2/commit/c2c67f2d9176e7bd3a208f8229272baa63bfff2c), [b0b5c3a](https://github.com/n0sfer666/FSD-Task-2/commit/b0b5c3aa0c654a36f98b168f45ed473f0f58265a), [278fdb0](https://github.com/n0sfer666/FSD-Task-2/commit/278fdb06bea94df9f68a51d7c4894e18cdedbb5c)).
> Закралась крамольная мысль, что необходимо было сделать другое, но пока оставлю так...

Тут я бы сделал всё одним блоком, с выбором типа заголовка

**Comment by n0sfer666** [comment]
Поправил (3469a91)
