### ISSUE TITLE
Независимость блоков

### ISSUE THREAD

**Issue by Everrest1** [n0sfer666/ui-kit__formElements#28]
Блок почему-то взаимодействует с внутренней структуре другого блока, созавая зависимость и нарушая инкапсуляцию.

![image](https://user-images.githubusercontent.com/43137324/87120213-fe8db380-c290-11ea-948f-ebe51260487b.png)

С блоком pagination тоже самое

**Comment by Everrest1** [comment]
Ничего не изменилось
Тебе нужно импортировать экземляр класса этого блока и работать только с его интерфейсом

![image](https://user-images.githubusercontent.com/43137324/87503113-6dde1b80-c674-11ea-988a-6c904841f405.png)
![image](https://user-images.githubusercontent.com/43137324/87503661-da0d4f00-c675-11ea-892e-d4ac90af85d0.png)

**Comment by Everrest1** [comment]
Здесь похожая проблема

![image](https://user-images.githubusercontent.com/43137324/87503192-a3830480-c674-11ea-9aeb-0333c10a49fb.png)

**Comment by n0sfer666** [comment]
> Ничего не изменилось
> Тебе нужно импортировать экземляр класса этого блока и работать только с его интерфейсом
> 
> ![image](https://user-images.githubusercontent.com/43137324/87503113-6dde1b80-c674-11ea-988a-6c904841f405.png)
> ![image](https://user-images.githubusercontent.com/43137324/87503661-da0d4f00-c675-11ea-892e-d4ac90af85d0.png)

Создал класс Button, сделал работу с кнопками "применить" и "очистить" через экземпляры, однако не смог изменить
конструкцию "$(`[data-id=${id}]`).find('.button-decrement')...", потому что эти кнопки создаются внешним модулем. (3619bc2)

**Comment by Everrest1** [comment]
Не, немного не так это делается. Ты можешь инициализировать инстанс класса кнопки прямо в datepicker, не нужно инициализировать и фильтровать все кнопки по модификатору, это очень не надёжно.
Например, в фале init.js ты нашёл элементы блока `dropdown` по имени класса, затем ищешь среди его дочерних элементов кнопку по имени класса, после этого можешь инициализировать инстанс `dropdown` и передать DOM элемент кнопки в конструктор. 
Либо при инициализации класса кнопки ты можешь передать в конструктор элемент `dropdown` и производить поиск кнопки по DOM уже в нём.

Касаемо этого кода, что возвращает этот селект `$(`[data-id=${id}]`)`? Распиши подробнее откуда сейчас эти кнопки?

![image](https://user-images.githubusercontent.com/43137324/88758515-ace29580-d179-11ea-98f0-c5f48663130e.png)

**Comment by n0sfer666** [comment]
Сделал рефакторинг дропдауна вот так e4b70de.
селектор $([data-id=${id}]) возвращает один из подчеркнутых элементов:
![image](https://user-images.githubusercontent.com/21785370/89298405-f8aba800-d66d-11ea-8e1f-ff52f5802a03.png)

Кнопки создаются при инициализации iqDropdown(this.getConfig()) в блоке iqdropdown-item-controls:
![image](https://user-images.githubusercontent.com/21785370/89304351-0402d180-d676-11ea-9893-943d57441529.png)

**Comment by n0sfer666** [comment]
Сделаю рефакторинг date-dropdown, после позитивной оценки рефакторинга dropdown.

**Comment by Everrest1** [comment]
Да, неплохо получилось

Тут, чтобы не тянуть DOM элемент из объекта, можно создать метод для кнопки `addEventListener` и через него вешать события

![image](https://user-images.githubusercontent.com/43137324/89429714-f40af080-d74e-11ea-919f-68c4c21b81d0.png)

**Comment by Everrest1** [comment]
Тут всё же будет лучше, если объект кнопки будет сам производить селект по классу. Сейчас дропдаун имеет представление о классе кнопки и что у неё есть модификатор, это нарушает инкапсуляцию и появляются зависимости. Например, если понадобится поменять название класса у кнопки, то нужно будет искать все места, где она используется и там менять тоже.

![image](https://user-images.githubusercontent.com/43137324/89430424-ca9e9480-d74f-11ea-9df4-fd9d95758082.png)

**Comment by n0sfer666** [comment]
> Да, неплохо получилось
> 
> Тут, чтобы не тянуть DOM элемент из объекта, можно создать метод для кнопки `addEventListener` и через него вешать события
> 
> ![image](https://user-images.githubusercontent.com/43137324/89429714-f40af080-d74e-11ea-919f-68c4c21b81d0.png)



> Тут всё же будет лучше, если объект кнопки будет сам производить селект по классу. Сейчас дропдаун имеет представление о классе кнопки и что у неё есть модификатор, это нарушает инкапсуляцию и появляются зависимости. Например, если понадобится поменять название класса у кнопки, то нужно будет искать все места, где она используется и там менять тоже.
> 
> ![image](https://user-images.githubusercontent.com/43137324/89430424-ca9e9480-d74f-11ea-9df4-fd9d95758082.png)

Исправил (56b6919)

**Comment by n0sfer666** [comment]
Сделал по аналогии с date-dropdown (3c6a314)

**Comment by Everrest1** [comment]
Тут можно за раз всё деструктуризировать

![image](https://user-images.githubusercontent.com/43137324/89978556-d7a31280-dc7e-11ea-9bac-868c558beca4.png)

**Comment by Everrest1** [comment]
Лучше сделать метод isActive()

![image](https://user-images.githubusercontent.com/43137324/89978827-73cd1980-dc7f-11ea-977a-a4d672c8d667.png)

**Comment by Everrest1** [comment]
Ну и, кстати, не будет ничего плохого, если кнопка будет знать, что она `apply` или `clear`, текущий способ определения функции по состоянию не очень надёжный, если, например, оно изменится, то это приведёт к неявным ошибкам в работе интерфейса.
Возможно, стоит сделать данный тип кнопок отдельным блоком, т.к. уже получается довольно специфичное применение.

**Comment by Hahahayabanan** [comment]
Много лишних действий получилось. Лучше, наверное, сразу выполнять всё в отдельном кейсе. И почему нам нужно удалить исходный элемент?

![image](https://user-images.githubusercontent.com/43137324/89979311-7ed47980-dc80-11ea-905d-7835b1b14b4a.png)

**Comment by Everrest1** [comment]
Ага, не увидел сразу. Здесь получается ты к каждому инпуту задаёшь свой отдельный календарь? Так не должно быть. Должен быть один календарь и два инпута, которые его вызывают

![image](https://user-images.githubusercontent.com/43137324/89979577-281b6f80-dc81-11ea-835b-42822519ea87.png)

**Comment by n0sfer666** [comment]
> Тут можно за раз всё деструктуризировать
> 
> ![image](https://user-images.githubusercontent.com/43137324/89978556-d7a31280-dc7e-11ea-9bac-868c558beca4.png)

Сделал (2d40708)

**Comment by n0sfer666** [comment]
> Ну и, кстати, не будет ничего плохого, если кнопка будет знать, что она `apply` или `clear`, текущий способ определения функции по состоянию не очень надёжный, если, например, оно изменится, то это приведёт к неявным ошибкам в работе интерфейса.
> Возможно, стоит сделать данный тип кнопок отдельным блоком, т.к. уже получается довольно специфичное применение.

Сделал компоненту button-clear-apply (b3dcea9), отрефакторил dropdown (5f8534e) и date-dropdown (0e498d0)

**Comment by n0sfer666** [comment]
> Ага, не увидел сразу. Здесь получается ты к каждому инпуту задаёшь свой отдельный календарь? Так не должно быть. Должен быть один календарь и два инпута, которые его вызывают
> 
> ![image](https://user-images.githubusercontent.com/43137324/89979577-281b6f80-dc81-11ea-835b-42822519ea87.png)

Сделал (da673cc)

**Comment by Everrest1** [comment]
> > Ну и, кстати, не будет ничего плохого, если кнопка будет знать, что она `apply` или `clear`, текущий способ определения функции по состоянию не очень надёжный, если, например, оно изменится, то это приведёт к неявным ошибкам в работе интерфейса.
> > Возможно, стоит сделать данный тип кнопок отдельным блоком, т.к. уже получается довольно специфичное применение.
> 
> Сделал компоненту button-clear-apply ([b3dcea9](https://github.com/n0sfer666/FSD-Task-2/commit/b3dcea9f864ccaabb977540f66585b79137a9050)), отрефакторил dropdown ([5f8534e](https://github.com/n0sfer666/FSD-Task-2/commit/5f8534eab0ed3060958ce46f316da3b421818e7c)) и date-dropdown ([0e498d0](https://github.com/n0sfer666/FSD-Task-2/commit/0e498d0cc408d484ee4bdc07c00d1e8df5d2c7f4))

Теперь здесь класс блока не соответствует имени блока. И название `button-clear-apply` не очень удачное. 
А тип кнопки, можно хранить в data атрибуте, к примеру. Либо изменять не класс блока, а элемента блока.
Ну и параметр тогда не булева, а какой-нибудь ключ-значение

![image](https://user-images.githubusercontent.com/43137324/90971716-b9ad9b80-e523-11ea-982f-005812222e95.png)

**Comment by Everrest1** [comment]
Тянет на два разных блока. Иконки соц сетей тоже можно вынести

![image](https://user-images.githubusercontent.com/43137324/90972024-ae0fa400-e526-11ea-95bb-7046dc059667.png)

**Comment by n0sfer666** [comment]
> Тянет на два разных блока. Иконки соц сетей тоже можно вынести
> 
> ![image](https://user-images.githubusercontent.com/43137324/90972024-ae0fa400-e526-11ea-95bb-7046dc059667.png)

Создал два компонента (b3264ea, a8d03a5);
Вынес кнопки соц.сетей в отдельный компонент (c473549);
Отрефакторил страницы (feea519);
Удалил старую компоненту футера (e369ee8);

**Comment by n0sfer666** [comment]
> Теперь здесь класс блока не соответствует имени блока. И название `button-clear-apply` не очень удачное.
> А тип кнопки, можно хранить в data атрибуте, к примеру. Либо изменять не класс блока, а элемента блока.
> Ну и параметр тогда не булева, а какой-нибудь ключ-значение
> 
> ![image](https://user-images.githubusercontent.com/43137324/90971716-b9ad9b80-e523-11ea-982f-005812222e95.png)

Переименовал в button-module + подкорректировал класс элемента, но архитектурно ничего не поменял (d2aba20)

**Comment by Everrest1** [comment]
Блок не должен знать детали реализации других блоков. Гибкость обеспечиваем модификаторами, а положение родительским элементом-обёрткой

![image](https://user-images.githubusercontent.com/43137324/91873294-e67f5280-ec89-11ea-8177-ed2113f77e07.png)

**Comment by Everrest1** [comment]
Снова селект DOM-узла другого блока по классу. 
И зачем здесь `element.remove()`?
Что такое 0 в параметре конструктора `control-button`?

![image](https://user-images.githubusercontent.com/43137324/91881394-7b864980-ec92-11ea-923c-71748253b1a2.png)

**Comment by n0sfer666** [comment]
> Снова селект DOM-узла другого блока по классу.
> И зачем здесь `element.remove()`?
Эти элементы добавляются в pug и их нужно удалить, чтобы потом засунуть во всплывающую форму.
> Что такое 0 в параметре конструктора `control-button`?
Убрал (это необязательный параметр)
> 
> ![image](https://user-images.githubusercontent.com/43137324/91881394-7b864980-ec92-11ea-923c-71748253b1a2.png)

**Comment by n0sfer666** [comment]
> Блок не должен знать детали реализации других блоков. Гибкость обеспечиваем модификаторами, а положение родительским элементом-обёрткой
> 
> ![image](https://user-images.githubusercontent.com/43137324/91873294-e67f5280-ec89-11ea-8177-ed2113f77e07.png)

Исправил (930d9dc)

**Comment by Everrest1** [comment]
Насчёт 0 в control-button, что это поле? Оно не используется нигде

![image](https://user-images.githubusercontent.com/43137324/92305079-d79fe500-ef94-11ea-9ac1-a79ec1ff8725.png)

**Comment by Everrest1** [comment]
Блок `date-dropdown` не должен знать, что у блока `control-button` есть класс `js-control-button`. Любой блок не должен знать ничего о внутренней реализации других блоков, а работать только с публичными методами

![image](https://user-images.githubusercontent.com/43137324/92305122-3f563000-ef95-11ea-8ab9-8809a875a9ec.png)

**Comment by n0sfer666** [comment]
> Насчёт 0 в control-button, что это поле? Оно не используется нигде
> 
> ![image](https://user-images.githubusercontent.com/43137324/92305079-d79fe500-ef94-11ea-9ac1-a79ec1ff8725.png)

Удалил везде index (362fad2). Изначально, когда делал, думал понадобится... не понадобилось.

**Comment by n0sfer666** [comment]
> Блок `date-dropdown` не должен знать, что у блока `control-button` есть класс `js-control-button`. Любой блок не должен знать ничего о внутренней реализации других блоков, а работать только с публичными методами
> 
> ![image](https://user-images.githubusercontent.com/43137324/92305122-3f563000-ef95-11ea-8ab9-8809a875a9ec.png)

Исправил в date-dropdown и dropdown (0cafa36, f1dd7d8, a251d7b, 6a108b8)

**Comment by Everrest1** [comment]
Позиционирование делается через обёртку

![image](https://user-images.githubusercontent.com/43137324/92621907-7ac66680-f2d5-11ea-9293-be49479c0e38.png)
![image](https://user-images.githubusercontent.com/43137324/92621943-86b22880-f2d5-11ea-9eac-f4b06f1d2ebc.png)

**Comment by n0sfer666** [comment]
> Позиционирование делается через обёртку
> 
> ![image](https://user-images.githubusercontent.com/43137324/92621907-7ac66680-f2d5-11ea-9293-be49479c0e38.png)
> ![image](https://user-images.githubusercontent.com/43137324/92621943-86b22880-f2d5-11ea-9eac-f4b06f1d2ebc.png)

Исправил во всех местах, где нашёл (7ac1872, c83ed35, 4851915, bb9530e)
