### ISSUE TITLE
структура проекта

### ISSUE THREAD

**Issue by DaRkLoL1** [n0sfer666/ui-kit__formElements#3]
В папке компонент должны лежать только компоненты у тебя там же лежат переменные миксины и шрифты их нужно вынести. Еще в некоторых компонентам лежат другие компоненты, их нужно разнести по разным компонентам. В компоненте должно лежать только вся логика, разметка, стили и картинки этого компонента, вкладывать компоненты запрещается. Да еще у тебя картинки которые используются в компонентах лежат в папке page их тоже нужно разбить по компонентам.

**Comment by n0sfer666** [comment]
done

**Comment by DaRkLoL1** [comment]
![Скриншот 11-05-2020 17_06_39](https://user-images.githubusercontent.com/32780725/81570875-d75a5900-93a9-11ea-90ed-8096eb3db85b.png)
это у тебя уже компоненты получается) и названия у  них ни понятно что обозначают c и t 
И include нужно в начале файла обьявлять)

**Comment by n0sfer666** [comment]
Создал 2 компонента color-block и type-block (pug + scss).
Нашел подобную ошибку в header и footer. Создал компонент header-menu-link и footer-menu-block (pug + scss).

**Comment by Everrest1** [comment]
Думаю, можно закрыть

**Comment by n0sfer666** [comment]
yep
