### ISSUE TITLE
Переопределение классов js

### ISSUE THREAD

**Issue by Everrest1** [n0sfer666/ui-kit__formElements#30]
Переопределяя свойство className у элемента ты заменяешь все его классы на указанный строковый литерал. Для этого есть другие методы.

![image](https://user-images.githubusercontent.com/43137324/87878919-5c8c6a80-c9f8-11ea-9872-a79eb8895404.png)

**Comment by n0sfer666** [comment]
Заменил на element.classList.remove и add (2091aba)
