### ISSUE TITLE
Использование let

### ISSUE THREAD

**Issue by Everrest1** [n0sfer666/ui-kit__formElements#31]
Использование const всегда лучше, а если есть необходимость в let, то нужно стараться избежать её

![image](https://user-images.githubusercontent.com/43137324/88759809-9c7fea00-d17c-11ea-9294-5be8b2b7a4d9.png)

**Comment by n0sfer666** [comment]
Исправил все pug'и, кроме search-room (могу исправить, но хотелось бы оставить, чтобы страничка более органично выглядела):
![image](https://user-images.githubusercontent.com/21785370/89120099-2b15a380-d4bc-11ea-8df9-781c69fedbe6.png)
 (3b2f2f2, 86bab1b, f364906, 6eeb171)

**Comment by n0sfer666** [comment]
Исправил в js (кроме нескольких моментов)

(cc6aa37)

**Comment by Everrest1** [comment]
> Исправил в js (кроме нескольких моментов)
> 
> ([cc6aa37](https://github.com/n0sfer666/FSD-Task-2/commit/cc6aa378c07dc376e5e2d364edaab9d6bcbdc6d2))

Глянул эти моменты, в каждом из них можно обойтись без `let`, если что пиши, подскажу как

**Comment by n0sfer666** [comment]
Исправил (4b9842d, 4bf1bcd, 044ba81).
Осталось:
pagination.js
![image](https://user-images.githubusercontent.com/21785370/89738633-dc02dc00-da82-11ea-93ce-e1fbe5a88bb4.png)
search-room.pug
![image](https://user-images.githubusercontent.com/21785370/89738644-f1780600-da82-11ea-81a4-8b9f12fe4a6d.png)

**Comment by Everrest1** [comment]
> Исправил ([4b9842d](https://github.com/n0sfer666/FSD-Task-2/commit/4b9842d2f3b02a2640e0ee0bf122e222088e89a8), [4bf1bcd](https://github.com/n0sfer666/FSD-Task-2/commit/4bf1bcdb211a3cc3a9f6f49da077749be4300d38), [044ba81](https://github.com/n0sfer666/FSD-Task-2/commit/044ba81bef3fb7e983635e75d4001b1a5dd77e5f)).
> Осталось:
> pagination.js
> ![image](https://user-images.githubusercontent.com/21785370/89738633-dc02dc00-da82-11ea-93ce-e1fbe5a88bb4.png)
> search-room.pug
> ![image](https://user-images.githubusercontent.com/21785370/89738644-f1780600-da82-11ea-81a4-8b9f12fe4a6d.png)

В первом случае точно можно заменить методом fill() вместе с конструктором Array, во втором, думаю тоже, надо попробовать

**Comment by n0sfer666** [comment]
В pagination.js использовал fill (58ff96c), Неправильно понял как работает метод, пришлось поправить (a83e620).
В search-room.pug заменил конструкцию for( let i...) на while (7ff1a32).

**Comment by n0sfer666** [comment]
Забыл удалить ненужную переменную, и опечатался в тексте коммита)) (4258e7d)
