### ISSUE TITLE
Миксы

### ISSUE THREAD

**Issue by Everrest1** [n0sfer666/ui-kit__formElements#36]
По стандартам п.5 https://github.com/fullstack-development/front-end-best-practices/blob/master/CSS/bem.md 

![image](https://user-images.githubusercontent.com/43137324/89433293-346c6d80-d753-11ea-95ce-be756c712fb0.png)

**Comment by n0sfer666** [comment]
Исправил (bea5d9f)

**Comment by Everrest1** [comment]
![image](https://user-images.githubusercontent.com/43137324/89979916-d9baa080-dc81-11ea-9570-bd21fcb8046b.png)

**Comment by n0sfer666** [comment]
Исправил, но промахнулся ишью (123cd7d)

**Comment by Everrest1** [comment]
Миксы)

![image](https://user-images.githubusercontent.com/43137324/90614350-9c26bc00-e21b-11ea-9ba0-b9f68e833834.png)

**Comment by n0sfer666** [comment]
Исправил (25d426a)
