### ISSUE TITLE
Структура страниц

### ISSUE THREAD

**Issue by Everrest1** [n0sfer666/ui-kit__formElements#38]
Pug позволяет использовать отдельную страницу template, например, для шапки, хэдера и футера, а затем вызывать этот темплейт на разных страницах, размещая на них только блок с контентом

**Comment by Everrest1** [comment]
Это должен делать сборщик автоматически, нет?

![image](https://user-images.githubusercontent.com/43137324/89980198-767d3e00-dc82-11ea-8d9a-ed532796bc57.png)

**Comment by Everrest1** [comment]
Это должно быть папке с блоком

![image](https://user-images.githubusercontent.com/43137324/89980288-a7f60980-dc82-11ea-8d0b-4b47a9115036.png)

**Comment by n0sfer666** [comment]
> Это должен делать сборщик автоматически, нет?
> 
> ![image](https://user-images.githubusercontent.com/43137324/89980198-767d3e00-dc82-11ea-8d9a-ed532796bc57.png)

Переместил script(src="main.min.js") в компонент head (изначально, так и было, но в прошлых ишью переделывал не помню уже зачем) (d0e85d5)
Переделал на автоматическую инъекцию (c68f731)

**Comment by n0sfer666** [comment]
> Это должно быть папке с блоком
> 
> ![image](https://user-images.githubusercontent.com/43137324/89980288-a7f60980-dc82-11ea-8d0b-4b47a9115036.png)

Перенёс в date-dropdown-init.js (7391676)

**Comment by n0sfer666** [comment]
> Pug позволяет использовать отдельную страницу template, например, для шапки, хэдера и футера, а затем вызывать этот темплейт на разных страницах, размещая на них только блок с контентом

Создал template (components/template/template.pug) (e589d19). Отрефакторил страницы (66d978b).

**Comment by Everrest1** [comment]
Тег body мы не трогаем
![image](https://user-images.githubusercontent.com/43137324/90615031-8fef2e80-e21c-11ea-84d5-8b1a34000008.png)

Здесь теги header и footer кажутся лишними
![image](https://user-images.githubusercontent.com/43137324/90615055-9b425a00-e21c-11ea-8383-707230aec00f.png)

**Comment by Everrest1** [comment]
template.pug стоит перенести к остальным страницам

**Comment by Everrest1** [comment]
Думаю, лучше будет сразу передавать литерал объекта в миксин. В читаемости не сильно большая разница, но хотя бы не нужно объявлять лишних переменных

![image](https://user-images.githubusercontent.com/43137324/90615683-83b7a100-e21d-11ea-9ec6-c16ca7199eaa.png)

**Comment by Everrest1** [comment]
Старый код)

![image](https://user-images.githubusercontent.com/43137324/90615865-b9f52080-e21d-11ea-8c92-5bbaf78fcbb1.png)

**Comment by Everrest1** [comment]
Тут тоже не понятно зачем такая структура

![image](https://user-images.githubusercontent.com/43137324/90615952-d5602b80-e21d-11ea-8bf1-cc8de66bea2e.png)

**Comment by n0sfer666** [comment]
Всё исправил.
Сделал 2 отдельных шаблона template-ui-kit и template-page (удобнее получается)

**Comment by Everrest1** [comment]
Может лучше делать импорт, там где эта компонента непосредственно используется?

![image](https://user-images.githubusercontent.com/43137324/90972081-270efb80-e527-11ea-8925-768cc307ecc0.png)

**Comment by Everrest1** [comment]
Просто класс из неоткуда

![image](https://user-images.githubusercontent.com/43137324/90972133-7fde9400-e527-11ea-8da9-33b85b2b8531.png)

**Comment by Everrest1** [comment]
Это теперь лишний блок?

![image](https://user-images.githubusercontent.com/43137324/90972138-997fdb80-e527-11ea-8d31-41af1fa383d3.png)

**Comment by n0sfer666** [comment]
> Может лучше делать импорт, там где эта компонента непосредственно используется?
> 
> ![image](https://user-images.githubusercontent.com/43137324/90972081-270efb80-e527-11ea-8925-768cc307ecc0.png)

Сделал (711d6e8, c1bc51f). Так лучше (быстрее компиляция)



> Просто класс из неоткуда
> 
> ![image](https://user-images.githubusercontent.com/43137324/90972133-7fde9400-e527-11ea-8da9-33b85b2b8531.png)

Удалил (14cb0dc)



> Это теперь лишний блок?
> 
> ![image](https://user-images.githubusercontent.com/43137324/90972138-997fdb80-e527-11ea-8d31-41af1fa383d3.png)

Удалил (070311e)

**Comment by Everrest1** [comment]
Откуда здесь взялся ` .inline-datepicker.js-inline-datepicker`?
Модификатор - это имя прилагательное в английском языке. По стандартам п.1 https://github.com/fullstack-development/front-end-best-practices/blob/master/CSS/bem.md

![image](https://user-images.githubusercontent.com/43137324/91601042-08bb5c80-e97a-11ea-8452-486002c20a81.png)

**Comment by Everrest1** [comment]
Имя класса и файла не совпадают

![image](https://user-images.githubusercontent.com/43137324/91601759-3fde3d80-e97b-11ea-9bbf-44cc1a980466.png)
![image](https://user-images.githubusercontent.com/43137324/91601786-4ec4f000-e97b-11ea-93f6-72a7d47a1abd.png)

**Comment by Everrest1** [comment]
Почему бы не дать тегу `a` этот класс?

![image](https://user-images.githubusercontent.com/43137324/91601923-816ee880-e97b-11ea-82fa-9613ece06358.png)

**Comment by n0sfer666** [comment]
> Почему бы не дать тегу `a` этот класс?
> 
> ![image](https://user-images.githubusercontent.com/43137324/91601923-816ee880-e97b-11ea-82fa-9613ece06358.png)

Отрефакторил сначала неправильно (d24a834), потом правильно, надеюсь (83ace31)


> Имя класса и файла не совпадают
> 
> ![image](https://user-images.githubusercontent.com/43137324/91601759-3fde3d80-e97b-11ea-9bbf-44cc1a980466.png)
> ![image](https://user-images.githubusercontent.com/43137324/91601786-4ec4f000-e97b-11ea-93f6-72a7d47a1abd.png)

Переименовал (8cd284c)

**Comment by n0sfer666** [comment]
> Откуда здесь взялся ` .inline-datepicker.js-inline-datepicker`?
> Модификатор - это имя прилагательное в английском языке. По стандартам п.1 https://github.com/fullstack-development/front-end-best-practices/blob/master/CSS/bem.md
> 
> ![image](https://user-images.githubusercontent.com/43137324/91601042-08bb5c80-e97a-11ea-8452-486002c20a81.png)

Сделал .date-dropdown_inline (2eccb28).
Кстати, не знаешь как туда кнопки засунуть? (onShow не работает с inline: true)

**Comment by Everrest1** [comment]
Не совпадают имена

![image](https://user-images.githubusercontent.com/43137324/91871119-33622980-ec88-11ea-9037-3078ace13675.png)
![image](https://user-images.githubusercontent.com/43137324/91871369-44129f80-ec88-11ea-8467-1198beb81182.png)

**Comment by Everrest1** [comment]
Модификатор `_320-px` не соответствует именованию БЭМ
Модификатор `date-dropdown_inline` используется вне своего блока

![image](https://user-images.githubusercontent.com/43137324/91872455-f2b6e000-ec88-11ea-9bb3-35b9c761d933.png)

**Comment by n0sfer666** [comment]
> Не совпадают имена
> 
> ![image](https://user-images.githubusercontent.com/43137324/91871119-33622980-ec88-11ea-9037-3078ace13675.png)
> ![image](https://user-images.githubusercontent.com/43137324/91871369-44129f80-ec88-11ea-8467-1198beb81182.png)

Переименовал файлы (2bb1191)

**Comment by n0sfer666** [comment]
> Модификатор `_320-px` не соответствует именованию БЭМ
> Модификатор `date-dropdown_inline` используется вне своего блока
> 
> ![image](https://user-images.githubusercontent.com/43137324/91872455-f2b6e000-ec88-11ea-9bb3-35b9c761d933.png)

Поправил (a9ed6d8, 246892c)

**Comment by Everrest1** [comment]
`js-pagination` вне своего блока или без миксина

![image](https://user-images.githubusercontent.com/43137324/92300422-a363fe80-ef6b-11ea-9155-227bb8ccd4ed.png)

**Comment by n0sfer666** [comment]
> `js-pagination` вне своего блока или без миксина
> 
> ![image](https://user-images.githubusercontent.com/43137324/92300422-a363fe80-ef6b-11ea-9155-227bb8ccd4ed.png)

Создал миксин и отрефакторил страницы (5bd4b7d)
UPD. Немного переделал (fd1d7e7)
