### ISSUE TITLE
Захардкоженность

### ISSUE THREAD

**Issue by Everrest1** [n0sfer666/ui-kit__formElements#39]
Стараемся вынести все данные, которые могут измениться со временем

![DeepinScreenshot_select-area_20200819131851](https://user-images.githubusercontent.com/43137324/90616847-03923b00-e21f-11ea-82b1-82a85851b2fc.png)

**Comment by n0sfer666** [comment]
Исправил (c65f2a5)

**Comment by Everrest1** [comment]
Можно и placeholder'ы вынести

![image](https://user-images.githubusercontent.com/43137324/90971901-486ee800-e525-11ea-8efb-83117dd51562.png)

**Comment by Everrest1** [comment]
И title

![image](https://user-images.githubusercontent.com/43137324/90971911-68061080-e525-11ea-9786-f45ffa1b31e7.png)

**Comment by Everrest1** [comment]
Кейсы можно передавать массивом объектов

![image](https://user-images.githubusercontent.com/43137324/90971938-c8954d80-e525-11ea-8e98-9b8c344bfee4.png)

**Comment by Everrest1** [comment]
Тут мы тоже их можем захотеть поменять

![image](https://user-images.githubusercontent.com/43137324/90971967-009c9080-e526-11ea-9699-85743e1daa00.png)

**Comment by Everrest1** [comment]
Это прокидываем сверху. Пройдись по проекту, часто встречается

![image](https://user-images.githubusercontent.com/43137324/90971975-1ca03200-e526-11ea-8b4c-ae414fdb1b46.png)

**Comment by n0sfer666** [comment]
> Можно и placeholder'ы вынести
> 
> ![image](https://user-images.githubusercontent.com/43137324/90971901-486ee800-e525-11ea-8efb-83117dd51562.png)



> И title
> 
> ![image](https://user-images.githubusercontent.com/43137324/90971911-68061080-e525-11ea-9786-f45ffa1b31e7.png)



> Кейсы можно передавать массивом объектов
> 
> ![image](https://user-images.githubusercontent.com/43137324/90971938-c8954d80-e525-11ea-8e98-9b8c344bfee4.png)



> Кейсы можно передавать массивом объектов
> 
> ![image](https://user-images.githubusercontent.com/43137324/90971938-c8954d80-e525-11ea-8e98-9b8c344bfee4.png)



> Тут мы тоже их можем захотеть поменять
> 
> ![image](https://user-images.githubusercontent.com/43137324/90971967-009c9080-e526-11ea-9699-85743e1daa00.png)

Исправил (aecc121)

**Comment by n0sfer666** [comment]
> Это прокидываем сверху. Пройдись по проекту, часто встречается
> 
> ![image](https://user-images.githubusercontent.com/43137324/90971975-1ca03200-e526-11ea-8b4c-ae414fdb1b46.png)

Исправил в другом ишью #38 (711d6e8, c1bc51f)

**Comment by Everrest1** [comment]
Не, это параметры миксина должны быть, для этого и выносим, чтобы была возможность изменить эти значения из вне

![image](https://user-images.githubusercontent.com/43137324/91602782-f7c01a80-e97c-11ea-9e09-61741ed20f98.png)

**Comment by n0sfer666** [comment]
> Не, это параметры миксина должны быть, для этого и выносим, чтобы была возможность изменить эти значения из вне
> 
> ![image](https://user-images.githubusercontent.com/43137324/91602782-f7c01a80-e97c-11ea-9e09-61741ed20f98.png)

Сделано (a24c258)

**Comment by Everrest1** [comment]
Dropdown сейчас захаркожен для работы только с гостями и мебелью. В будущем может понадобиться использовать его в другом контексте

![image](https://user-images.githubusercontent.com/43137324/92305186-e8048f80-ef95-11ea-9f29-6298fb96c293.png)
![image](https://user-images.githubusercontent.com/43137324/92305189-f8b50580-ef95-11ea-8c2b-54c446273cdb.png)

**Comment by Everrest1** [comment]
Это тоже сверху должно приходить

![image](https://user-images.githubusercontent.com/43137324/92305202-197d5b00-ef96-11ea-80c1-a3cc19604729.png)

**Comment by n0sfer666** [comment]
> Это тоже сверху должно приходить
> 
> ![image](https://user-images.githubusercontent.com/43137324/92305202-197d5b00-ef96-11ea-80c1-a3cc19604729.png)

Исправлено (9104292)
UPD. Нашел еще 3 компоненты с похожей проблемой (a13f652, 9a82614)

**Comment by n0sfer666** [comment]
> Dropdown сейчас захаркожен для работы только с гостями и мебелью. В будущем может понадобиться использовать его в другом контексте
> 
> ![image](https://user-images.githubusercontent.com/43137324/92305186-e8048f80-ef95-11ea-9f29-6298fb96c293.png)

Сделал вот так b7d6af1

**Comment by Everrest1** [comment]
> > Dropdown сейчас захаркожен для работы только с гостями и мебелью. В будущем может понадобиться использовать его в другом контексте
> 
> Сделал вот так [b7d6af1](https://github.com/n0sfer666/FSD-Task-2/commit/b7d6af153db7d49c0b5387d98c1051742cff80ec)

Лучше, но это не решает вопрос, dropdown всё ещё нельзя использовать с чем-то кроме гостей и мебели. Нужно более абстрактное решение, которое было бы не привязано к контексту

**Comment by n0sfer666** [comment]
> Лучше, но это не решает вопрос, dropdown всё ещё нельзя использовать с чем-то кроме гостей и мебели. Нужно более абстрактное решение, которое было бы не привязано к контексту

Вынес всё в параметры миксина и переделал скрипт (762d1f4, b60a6f7)

**Comment by Everrest1** [comment]
Чёт перемудрил немного с dropdown))

Склонения слов можно прокинуть целым объектом
Можно прокинуть их в конструкторе класса js, а потом соотнести с id строки

![image](https://user-images.githubusercontent.com/43137324/94294917-91c1b580-ff71-11ea-8de8-bfae01ce89ba.png)

**Comment by Everrest1** [comment]
А ты не буферизируешь DOM-элементы этих row? Надо стараться избегать селекторов по атрибутам

![image](https://user-images.githubusercontent.com/43137324/94295546-71dec180-ff72-11ea-8357-191d54585f52.png)

![image](https://user-images.githubusercontent.com/43137324/94296417-e0704f00-ff73-11ea-870a-bf3c1fc98533.png)

**Comment by Everrest1** [comment]
Есть css свойство, которое троеточие ставит, если текст не умещается в контейнере)

![image](https://user-images.githubusercontent.com/43137324/94295683-a94d6e00-ff72-11ea-8322-2ff0827b55d1.png)

**Comment by n0sfer666** [comment]
> Чёт перемудрил немного с dropdown))
> 
> Склонения слов можно прокинуть целым объектом
> Можно прокинуть их в конструкторе класса js, а потом соотнести с id строки
> 
> ![image](https://user-images.githubusercontent.com/43137324/94294917-91c1b580-ff71-11ea-8de8-bfae01ce89ba.png)

Переделал (2d289ef, 6ca121e)

**Comment by n0sfer666** [comment]
> А ты не буферизируешь DOM-элементы этих row? Надо стараться избегать селекторов по атрибутам
> 
> ![image](https://user-images.githubusercontent.com/43137324/94295546-71dec180-ff72-11ea-8357-191d54585f52.png)
> 
> ![image](https://user-images.githubusercontent.com/43137324/94296417-e0704f00-ff73-11ea-870a-bf3c1fc98533.png)

Сделал (b886113)

**Comment by n0sfer666** [comment]
> Есть css свойство, которое троеточие ставит, если текст не умещается в контейнере)
> 
> ![image](https://user-images.githubusercontent.com/43137324/94295683-a94d6e00-ff72-11ea-8322-2ff0827b55d1.png)

Исправил (8c06246)
