### ISSUE TITLE
автоимпорт

### ISSUE THREAD

**Issue by DaRkLoL1** [n0sfer666/ui-kit__formElements#4]
У webpack есть возможность импорта всех scss, js, png и прочих файлов - посмотри в документации. У тебя сейчас куча файлов только для импортов.https://webpack.js.org/guides/dependency-management/#context-module-api

**Comment by n0sfer666** [comment]
done

**Comment by DaRkLoL1** [comment]
![Скриншот 25-04-2020 14_09_02](https://user-images.githubusercontent.com/32780725/80278369-58ed8e00-86fe-11ea-8c2e-f35c4964c9ca.png)
а зачем несколько раз importall вызывать для 1 пути можно importAll(require.context('./pages/', true, /\.scss|js$/)); указать
