### ISSUE TITLE
Переопределение аргументов

### ISSUE THREAD

**Issue by Everrest1** [n0sfer666/ui-kit__formElements#40]
Здесь переопределяется аргумент миксина, чего делать нельзя, плюс после нахождения искомого элемента цикл не останавливается.
Предлагаю отрефакторить с методом `indexOf`

А ещё тут у тебя два массива с почти одинаковыми значениями ячеек, может лучше использовать один?

![image](https://user-images.githubusercontent.com/43137324/90617153-64ba0e80-e21f-11ea-8f7f-e877bd804c7b.png)

Именование
`modKey` ненужное сокращение + лучше будет, если упомянуть в названии что это за модификтор
`styles` тут можно указать, что это массив с модификаторами

**Comment by Everrest1** [comment]
Тут всё тоже самое

![image](https://user-images.githubusercontent.com/43137324/90618336-ea8a8980-e220-11ea-88ac-275da58de375.png)

**Comment by Everrest1** [comment]
Можно вот как сделать

![image](https://user-images.githubusercontent.com/43137324/90618610-4d7c2080-e221-11ea-942f-c8ec5a957df5.png)

А потом извлекаешь значение по полученному сверху ключу: `const {hex, title} = colors[color]`

**Comment by n0sfer666** [comment]
Исправил.
Кнопка (a8b3f28);
Цвето-блок (4c15cec);
