### ISSUE TITLE
Фиксированная ширина

### ISSUE THREAD

**Issue by Everrest1** [n0sfer666/ui-kit__formElements#41]
Всегда стараемся избежать фиксированной ширины и высоты блоков, придерживаясь практики `responsive`

**Comment by n0sfer666** [comment]
Исправил 2 разновидности кнопки (с рамкой и с заливкой без стрелки) (2d1d806)
Исправил размер контейнера для комментариев на Form Elements (8192616)
В остальном изначально руководствовался рекомендациями [гугла](https://developers.google.com/web/fundamentals/design-and-ux/responsive?hl=ru)

**Comment by Everrest1** [comment]
Много где ещё осталась фиксированная высота и ширина

![image](https://user-images.githubusercontent.com/43137324/91873794-8806a400-ec8a-11ea-9b21-83b8c7b4b447.png)

**Comment by Everrest1** [comment]
![image](https://user-images.githubusercontent.com/43137324/91877405-006f6400-ec8f-11ea-8ebb-3bd69ea381fb.png)

![image](https://user-images.githubusercontent.com/43137324/91877365-f2b9de80-ec8e-11ea-8c79-c771f529d29d.png)

**Comment by n0sfer666** [comment]
Сделал вот так (e1d9230, 6c998e7, a2e8841)

**Comment by Everrest1** [comment]
Тут тоже не обязательно фиксированная ширина

![image](https://user-images.githubusercontent.com/43137324/92300482-2a18db80-ef6c-11ea-9188-736a62504d59.png)

**Comment by n0sfer666** [comment]
> Тут тоже не обязательно фиксированная ширина
> 
> ![image](https://user-images.githubusercontent.com/43137324/92300482-2a18db80-ef6c-11ea-9188-736a62504d59.png)

Исправил здесь и прошёлся по проекту (c26b81a)
