### ISSUE TITLE
Кодстайл

### ISSUE THREAD

**Issue by Everrest1** [n0sfer666/ui-kit__formElements#42]
Тут можно отформатировать в несколько строк

![image](https://user-images.githubusercontent.com/43137324/91601629-04dc0a00-e97b-11ea-945d-b4dca4d8ecf4.png)

**Comment by Everrest1** [comment]
Не уверен, что такая точность необходима)

![image](https://user-images.githubusercontent.com/43137324/91601992-a06d7a80-e97b-11ea-8a35-6b90aa104b29.png)

**Comment by Everrest1** [comment]
В pug это считай тот же javascript, поэтому используем одинарные апострофы. Делается очень легко, если у тебя VSCode

**Comment by Everrest1** [comment]
Лучше сначала объявить переменные, а потом начинать вёрстку

![image](https://user-images.githubusercontent.com/43137324/91603677-7e292c00-e97e-11ea-933e-3a6574ea9dce.png)

**Comment by n0sfer666** [comment]
> Тут можно отформатировать в несколько строк
> 
> ![image](https://user-images.githubusercontent.com/43137324/91601629-04dc0a00-e97b-11ea-945d-b4dca4d8ecf4.png)

Сделал (a3fe29b)

> Не уверен, что такая точность необходима)
> 
> ![image](https://user-images.githubusercontent.com/43137324/91601992-a06d7a80-e97b-11ea-8a35-6b90aa104b29.png)

К сожалению, необходима :) (иначе по pixelPerfect совсем всё печально)

> В pug это считай тот же javascript, поэтому используем одинарные апострофы. Делается очень легко, если у тебя VSCode

Сделал (1547d9c)

> Лучше сначала объявить переменные, а потом начинать вёрстку
> 
> ![image](https://user-images.githubusercontent.com/43137324/91603677-7e292c00-e97e-11ea-933e-3a6574ea9dce.png)

Сделал в color-block и еще 3х компонент (e28337e)

**Comment by Everrest1** [comment]
> > Не уверен, что такая точность необходима)
> > ![image](https://user-images.githubusercontent.com/43137324/91601992-a06d7a80-e97b-11ea-8a35-6b90aa104b29.png)
> 
> К сожалению, необходима :) (иначе по pixelPerfect совсем всё печально)
> 

Мне интересно, как ты рассчитал этот паддинг в процентах с точностью до десятитысячных

**Comment by Everrest1** [comment]
Стоило бы вынести svg код в отдельный файл. И что-то сомневаюсь в правильности делать иконку бэкграундом, выглядит как костыль

![image](https://user-images.githubusercontent.com/43137324/91880800-999f7a00-ec91-11ea-8933-d85f3b9f8cfe.png)

**Comment by n0sfer666** [comment]
> > > Не уверен, что такая точность необходима)
> > > ![image](https://user-images.githubusercontent.com/43137324/91601992-a06d7a80-e97b-11ea-8a35-6b90aa104b29.png)
> > 
> > 
> > К сожалению, необходима :) (иначе по pixelPerfect совсем всё печально)
> 
> Мне интересно, как ты рассчитал этот паддинг в процентах с точностью до десятитысячных

ширина контейнера 1440пкс = 100%, 140пкс = X%. Дальше, по правилам пропорции, получаем первые значения и корректируем в PixelPerfect.

**Comment by n0sfer666** [comment]
> Стоило бы вынести svg код в отдельный файл. И что-то сомневаюсь в правильности делать иконку бэкграундом, выглядит как костыль
> 
> ![image](https://user-images.githubusercontent.com/43137324/91880800-999f7a00-ec91-11ea-8933-d85f3b9f8cfe.png)

Сделал в этой компоненте и в 3х других (3da6d42).

**Comment by Everrest1** [comment]
> > > > Не уверен, что такая точность необходима)
> > > > ![image](https://user-images.githubusercontent.com/43137324/91601992-a06d7a80-e97b-11ea-8a35-6b90aa104b29.png)
> > > 
> > > 
> > > К сожалению, необходима :) (иначе по pixelPerfect совсем всё печально)
> > 
> > 
> > Мне интересно, как ты рассчитал этот паддинг в процентах с точностью до десятитысячных
> 
> ширина контейнера 1440пкс = 100%, 140пкс = X%. Дальше, по правилам пропорции, получаем первые значения и корректируем в PixelPerfect.

Как по мне padding в процентах добавляет неочевидности в вёрстку. Но если так хочешь, можешь сделать функцию по расчёту этих значений, а вот такие значения это ненужное усложнение, как по мне
![image](https://user-images.githubusercontent.com/43137324/92300599-36516880-ef6d-11ea-8005-6e3e5e11ba75.png)

**Comment by Everrest1** [comment]
Можно и без переменной литерал объекта передавать

![image](https://user-images.githubusercontent.com/43137324/92300735-4a499a00-ef6e-11ea-9278-427073c26e4f.png)

**Comment by n0sfer666** [comment]
> Можно и без переменной литерал объекта передавать
> 
> ![image](https://user-images.githubusercontent.com/43137324/92300735-4a499a00-ef6e-11ea-9278-427073c26e4f.png)

Исправил (31af018)

**Comment by n0sfer666** [comment]
> > > > > Не уверен, что такая точность необходима)
> > > > > ![image](https://user-images.githubusercontent.com/43137324/91601992-a06d7a80-e97b-11ea-8a35-6b90aa104b29.png)
> > > > 
> > > > 
> > > > К сожалению, необходима :) (иначе по pixelPerfect совсем всё печально)
> > > 
> > > 
> > > Мне интересно, как ты рассчитал этот паддинг в процентах с точностью до десятитысячных
> > 
> > 
> > ширина контейнера 1440пкс = 100%, 140пкс = X%. Дальше, по правилам пропорции, получаем первые значения и корректируем в PixelPerfect.
> 
> Как по мне padding в процентах добавляет неочевидности в вёрстку. Но если так хочешь, можешь сделать функцию по расчёту этих значений, а вот такие значения это ненужное усложнение, как по мне
> ![image](https://user-images.githubusercontent.com/43137324/92300599-36516880-ef6d-11ea-8005-6e3e5e11ba75.png)

Сделал расчёты в начале файлов стилей (92432a3)

**Comment by Everrest1** [comment]
Такое количество атрибутов лучше отформатировать в несколько строк

![image](https://user-images.githubusercontent.com/43137324/94294553-0c3e0580-ff71-11ea-8779-58353d455bd4.png)

**Comment by n0sfer666** [comment]
> Такое количество атрибутов лучше отформатировать в несколько строк
> 
> ![image](https://user-images.githubusercontent.com/43137324/94294553-0c3e0580-ff71-11ea-8779-58353d455bd4.png)

Исправил (6640883)

**Comment by Everrest1** [comment]
> > Такое количество атрибутов лучше отформатировать в несколько строк
> > ![image](https://user-images.githubusercontent.com/43137324/94294553-0c3e0580-ff71-11ea-8779-58353d455bd4.png)
> 
> Исправил ([6640883](https://github.com/n0sfer666/FSD-Task-2/commit/66408832c8078abeac7ed9adc0df655b657ea307))

Не, отформатируй, как это делается по стайлгайду, каждый атрибут на новой строке с отступом 2 пробела

**Comment by n0sfer666** [comment]
> > > Такое количество атрибутов лучше отформатировать в несколько строк
> > > ![image](https://user-images.githubusercontent.com/43137324/94294553-0c3e0580-ff71-11ea-8779-58353d455bd4.png)
> > 
> > 
> > Исправил ([6640883](https://github.com/n0sfer666/FSD-Task-2/commit/66408832c8078abeac7ed9adc0df655b657ea307))
> 
> Не, отформатируй, как это делается по стайлгайду, каждый атрибут на новой строке с отступом 2 пробела

Cделал (21e4f12)

**Comment by Everrest1** [comment]
Отступы

![image](https://user-images.githubusercontent.com/43137324/95547660-83b17180-0a14-11eb-8e33-e2269a9e2e1a.png)
![image](https://user-images.githubusercontent.com/43137324/95547689-9461e780-0a14-11eb-8a5e-26fb6ea515f1.png)
![image](https://user-images.githubusercontent.com/43137324/95549132-b6a93480-0a17-11eb-91f5-b4d863d6f0d9.png)
![image](https://user-images.githubusercontent.com/43137324/95549158-c9236e00-0a17-11eb-9a53-2cd6bbffa38a.png)
![image](https://user-images.githubusercontent.com/43137324/95549173-d0e31280-0a17-11eb-9183-ef470fb5344c.png)
![image](https://user-images.githubusercontent.com/43137324/95549187-d8a2b700-0a17-11eb-8e19-f7aa505ee6e7.png)
![image](https://user-images.githubusercontent.com/43137324/95549221-ea845a00-0a17-11eb-86b3-b1c68d54ec46.png)

**Comment by Everrest1** [comment]
css loader сам проставляет все префиксы, вроде как

![image](https://user-images.githubusercontent.com/43137324/95549367-36370380-0a18-11eb-8442-3eda5fb1aaa1.png)

**Comment by n0sfer666** [comment]
> css loader сам проставляет все префиксы, вроде как
> 
> ![image](https://user-images.githubusercontent.com/43137324/95549367-36370380-0a18-11eb-8442-3eda5fb1aaa1.png)

Вообще, нет (можно проверить [тут](https://autoprefixer.github.io/ru/)), но решение я нашел - ::placeholder { color: $color } (1d9bd0a)

**Comment by Everrest1** [comment]
Отступ

![image](https://user-images.githubusercontent.com/43137324/95612581-aecbad80-0a74-11eb-8324-5f6606d5c9c8.png)

**Comment by Everrest1** [comment]
А он ведь глобально ко всем элементам применён

![image](https://user-images.githubusercontent.com/43137324/95612686-dc185b80-0a74-11eb-8520-cd041e21b6bc.png)

**Comment by Everrest1** [comment]
Отступы((

![image](https://user-images.githubusercontent.com/43137324/95613233-afb10f00-0a75-11eb-8b45-80295a78e8f0.png)

**Comment by n0sfer666** [comment]
> Отступ
> 
> ![image](https://user-images.githubusercontent.com/43137324/95612581-aecbad80-0a74-11eb-8324-5f6606d5c9c8.png)



> Отступ
> 
> ![image](https://user-images.githubusercontent.com/43137324/95612581-aecbad80-0a74-11eb-8324-5f6606d5c9c8.png)



> А он ведь глобально ко всем элементам применён
> 
> ![image](https://user-images.githubusercontent.com/43137324/95612686-dc185b80-0a74-11eb-8520-cd041e21b6bc.png)

Исправил (da8be0e)

**Comment by n0sfer666** [comment]
> Отступы((
> 
> ![image](https://user-images.githubusercontent.com/43137324/95613233-afb10f00-0a75-11eb-8b45-80295a78e8f0.png)

Прошелся по всему проекту. Привёл всё к единому кодстайлу (27bfab0)

**Comment by Everrest1** [comment]
Отступ перед скобкой

![image](https://user-images.githubusercontent.com/43137324/96548197-77ec6780-12be-11eb-8558-603b12de3014.png)

**Comment by Everrest1** [comment]
Эти отступы между квадратными скобками выглядят странно

![image](https://user-images.githubusercontent.com/43137324/96548991-e7af2200-12bf-11eb-9c23-8ba62e7ebc43.png)

**Comment by n0sfer666** [comment]
> Отступ перед скобкой
> 
> ![image](https://user-images.githubusercontent.com/43137324/96548197-77ec6780-12be-11eb-8558-603b12de3014.png)



> Эти отступы между квадратными скобками выглядят странно
> 
> ![image](https://user-images.githubusercontent.com/43137324/96548991-e7af2200-12bf-11eb-9c23-8ba62e7ebc43.png)

Исправил (652e09d, 4447c8c)
