### ISSUE TITLE
Разные правки

### ISSUE THREAD

**Issue by Everrest1** [n0sfer666/ui-kit__formElements#43]
Заголовок можно вынести в параметры
Зачем тут `js-button-module_apply/_clear`, если можно получить тип кнопки из дата атрибута? Так, секунду, а что делает `dataType`?

![image](https://user-images.githubusercontent.com/43137324/91603209-a8c6b500-e97d-11ea-9b50-c11e428e6ed7.png)

**Comment by Everrest1** [comment]
Это нужно рефакторнуть. Попробуй или привести к одной структуре, чтобы не было дублирования.

![image](https://user-images.githubusercontent.com/43137324/91604066-132c2500-e97f-11ea-82c4-8c1cc9fdc1ed.png)

**Comment by n0sfer666** [comment]
> Заголовок можно вынести в параметры
> Зачем тут `js-button-module_apply/_clear`, если можно получить тип кнопки из дата атрибута? Так, секунду, а что делает `dataType`?
> 
> ![image](https://user-images.githubusercontent.com/43137324/91603209-a8c6b500-e97d-11ea-9b50-c11e428e6ed7.png)

Переделал (97202b8)

**Comment by n0sfer666** [comment]
> Это нужно рефакторнуть. Попробуй или привести к одной структуре, чтобы не было дублирования.
> 
> ![image](https://user-images.githubusercontent.com/43137324/91604066-132c2500-e97f-11ea-82c4-8c1cc9fdc1ed.png)

Сделал вот так (4b4c9b2), норм?

**Comment by Everrest1** [comment]
Модификатор используется вне своего элемента

![image](https://user-images.githubusercontent.com/43137324/92300709-0b1b4900-ef6e-11ea-8e0d-39be6a4d39ef.png)

**Comment by n0sfer666** [comment]
Исправил (6876692)

**Comment by Everrest1** [comment]
Почему дважды?

![image](https://user-images.githubusercontent.com/43137324/92621041-659d0800-f2d4-11ea-8fbe-d6fccb0a34e2.png)

**Comment by Everrest1** [comment]
Не надо мутировать инстанс библиотеки, сохрани результат отдельным методом

![image](https://user-images.githubusercontent.com/43137324/92621385-cd535300-f2d4-11ea-92ae-b1b94e833417.png)

**Comment by n0sfer666** [comment]
> Почему дважды?
> 
> ![image](https://user-images.githubusercontent.com/43137324/92621041-659d0800-f2d4-11ea-8fbe-d6fccb0a34e2.png)

Хотел бы я знать, но по другому работает криво (при нажатии на "очистить" нужен дополнительный клик, чтобы продолжить работу со страницей)

**Comment by n0sfer666** [comment]
> Не надо мутировать инстанс библиотеки, сохрани результат отдельным методом
> 
> ![image](https://user-images.githubusercontent.com/43137324/92621385-cd535300-f2d4-11ea-92ae-b1b94e833417.png)

Создал отдельный метод (bf419ac)

**Comment by Everrest1** [comment]
А почему строка в булевой переменной isActive?

![image](https://user-images.githubusercontent.com/43137324/95290604-b45fa280-087e-11eb-9c5a-069bd597ff6b.png)

**Comment by Everrest1** [comment]
Элемент вне блока

![image](https://user-images.githubusercontent.com/43137324/95291055-bf670280-087f-11eb-8c69-9e6d8878bb57.png)

**Comment by Everrest1** [comment]
Почему бы не инициализировать массив литералом

![image](https://user-images.githubusercontent.com/43137324/95291138-eae9ed00-087f-11eb-9867-bbb3d5f62135.png)

**Comment by Everrest1** [comment]
Валюту и дату можно вынести в параметр

![image](https://user-images.githubusercontent.com/43137324/95291315-50d67480-0880-11eb-852e-d16546ea2894.png)

**Comment by n0sfer666** [comment]
> А почему строка в булевой переменной isActive?
> 
Исправил в button и date-dropdown (e61aa78)

> Элемент вне блока
> 
Исправил (7528577)


> Почему бы не инициализировать массив литералом
> 
Сделал + поправил headline (ce7a14b)


> Валюту и дату можно вынести в параметр
> 
Исправил (d6c244c)

**Comment by Everrest1** [comment]
`callback` название не очень для метода
`.js-room__slider` из другого блока
`totalPage` можно заменить `_`

![image](https://user-images.githubusercontent.com/43137324/95606486-74114780-0a6b-11eb-8e6f-6a5ae485d2bf.png)

**Comment by Everrest1** [comment]
А зачем тут id? В темах есть такой вопрос про label
name, наверное, лучше параметром принимать

![image](https://user-images.githubusercontent.com/43137324/95612128-ec7c0680-0a73-11eb-9669-c97e593f1617.png)

**Comment by Everrest1** [comment]
Селектор другого блока

![image](https://user-images.githubusercontent.com/43137324/95612901-24377e00-0a75-11eb-9638-91a1675ce5e6.png)

**Comment by Everrest1** [comment]
Не понимаю что здесь происходит

![image](https://user-images.githubusercontent.com/43137324/95613040-5f39b180-0a75-11eb-836a-86aeab13e747.png)

**Comment by Everrest1** [comment]
`&_single`

![image](https://user-images.githubusercontent.com/43137324/95613323-d53e1880-0a75-11eb-826c-646326ee4cca.png)

**Comment by n0sfer666** [comment]
> `callback` название не очень для метода
> `.js-room__slider` из другого блока
> `totalPage` можно заменить `_`
> 

Переделал два класса + несколько правок по другим компонентам (26855a0)

**Comment by n0sfer666** [comment]
Переделал полностью компоненту (2bcb25b)

**Comment by n0sfer666** [comment]
> Селектор другого блока
> 
> ![image](https://user-images.githubusercontent.com/43137324/95612901-24377e00-0a75-11eb-9638-91a1675ce5e6.png)

Исправил (6b6de76)

> Не понимаю что здесь происходит
> 
> ![image](https://user-images.githubusercontent.com/43137324/95613040-5f39b180-0a75-11eb-836a-86aeab13e747.png)

Сделал более понятное решение + добавил инициализацию класса (2839b32)

> `&_single`
> 
> ![image](https://user-images.githubusercontent.com/43137324/95613323-d53e1880-0a75-11eb-826c-646326ee4cca.png)

Исправил (22514f5)

**Comment by Everrest1** [comment]
Зачем переименовал? Было нормально

![image](https://user-images.githubusercontent.com/43137324/96346569-80218880-10ad-11eb-8c22-7b1a77fd6a5a.png)

**Comment by Everrest1** [comment]
Можно переписать, используя метод `filter`

![image](https://user-images.githubusercontent.com/43137324/96346625-d55d9a00-10ad-11eb-944a-78eacc21c03e.png)

**Comment by Everrest1** [comment]
`find` возвращает значение первого найденного в массиве элемента

![image](https://user-images.githubusercontent.com/43137324/96346651-050ca200-10ae-11eb-9e79-e789cbfa1f8a.png)

**Comment by Everrest1** [comment]
Можно избежать дублирования

![image](https://user-images.githubusercontent.com/43137324/96346759-88c68e80-10ae-11eb-88cc-d25e0146a66a.png)

**Comment by n0sfer666** [comment]
> Зачем переименовал? Было нормально
> 
> ![image](https://user-images.githubusercontent.com/43137324/96346569-80218880-10ad-11eb-8c22-7b1a77fd6a5a.png)

Исправил. (bb32cb5)
Я экспериментировал с callback'ом (там есть параметр pagination), из-за этого пришлось переименовать, а обратно вернуть я забыл :(

**Comment by n0sfer666** [comment]
> `find` возвращает значение первого найденного в массиве элемента
> 
> ![image](https://user-images.githubusercontent.com/43137324/96346651-050ca200-10ae-11eb-9e79-e789cbfa1f8a.png)

.find( selector )Returns: jQuery
Description: Get the descendants of each element in the current set of matched elements, filtered by a selector, jQuery object, or element.

![image](https://user-images.githubusercontent.com/21785370/96364350-03d98480-1143-11eb-8556-c55fcd57a574.png)

![image](https://user-images.githubusercontent.com/21785370/96364336-e6a4b600-1142-11eb-9229-ce884442f5d6.png)

**Comment by n0sfer666** [comment]
> Можно переписать, используя метод `filter`
> 
> ![image](https://user-images.githubusercontent.com/43137324/96346625-d55d9a00-10ad-11eb-944a-78eacc21c03e.png)

Сделал (5ee3ff2)

**Comment by n0sfer666** [comment]
> Можно избежать дублирования
> 
> ![image](https://user-images.githubusercontent.com/43137324/96346759-88c68e80-10ae-11eb-88cc-d25e0146a66a.png)

Сделал так 47b167b

**Comment by Everrest1** [comment]
А зачем было переименовывать свойства в деструктуризации? Нагромождение такое.
`complementaryFee` отдельно почему-то

![image](https://user-images.githubusercontent.com/43137324/96546825-04495b00-12bc-11eb-8ff3-c0d405789999.png)

**Comment by Everrest1** [comment]
Лучше тут тернарником воспользоваться, чтобы избежать вложенности условий и не дублировать вызов метода `text`

![image](https://user-images.githubusercontent.com/43137324/96547411-1aa3e680-12bd-11eb-98d1-dc59b2823b84.png)

**Comment by n0sfer666** [comment]
> А зачем было переименовывать свойства в деструктуризации? Нагромождение такое.
> `complementaryFee` отдельно почему-то
> 
> ![image](https://user-images.githubusercontent.com/43137324/96546825-04495b00-12bc-11eb-8ff3-c0d405789999.png)

Переделал (a1fd8a5)



> Лучше тут тернарником воспользоваться, чтобы избежать вложенности условий и не дублировать вызов метода `text`
> 
> ![image](https://user-images.githubusercontent.com/43137324/96547411-1aa3e680-12bd-11eb-98d1-dc59b2823b84.png)

Переделал (27ae374)

**Comment by Everrest1** [comment]
Зачем конкатенация внутри шаблонной строки?

![image](https://user-images.githubusercontent.com/43137324/97395074-8e697300-18fd-11eb-92ba-09e02512244b.png)

**Comment by n0sfer666** [comment]
> Зачем конкатенация внутри шаблонной строки?
> 
> ![image](https://user-images.githubusercontent.com/43137324/97395074-8e697300-18fd-11eb-92ba-09e02512244b.png)

Думал, что можно в отдельную переменную не выносить... Переделал (f43b6c6)

**Comment by Everrest1** [comment]
Конкатенация осталась. Выражение тоже можно помещать в конструкцию `${daysIn === 1 ? ' сутки' : ' суток'}`

![image](https://user-images.githubusercontent.com/43137324/97882603-3be4e800-1d3d-11eb-98d1-eee0d03389a6.png)

**Comment by Everrest1** [comment]
Элемент блока находится вне блока

![image](https://user-images.githubusercontent.com/43137324/97883109-e1985700-1d3d-11eb-9974-2f66a7334774.png)

**Comment by n0sfer666** [comment]
> Конкатенация осталась. Выражение тоже можно помещать в конструкцию `${daysIn === 1 ? ' сутки' : ' суток'}`
> 
> ![image](https://user-images.githubusercontent.com/43137324/97882603-3be4e800-1d3d-11eb-98d1-eee0d03389a6.png)

Исправил (8830147)



> Элемент блока находится вне блока
> 
> ![image](https://user-images.githubusercontent.com/43137324/97883109-e1985700-1d3d-11eb-9974-2f66a7334774.png)

Исправил (f803664)

**Comment by Hahahayabanan** [comment]
Лишний отступ

![image](https://user-images.githubusercontent.com/43137324/98567005-e1adcf00-22c8-11eb-9c2e-a712357c1456.png)

**Comment by Everrest1** [comment]
Значения по умолчанию можно указать в параметрах миксина

![image](https://user-images.githubusercontent.com/43137324/98567463-613b9e00-22c9-11eb-930f-b974b702296b.png)

**Comment by n0sfer666** [comment]
> Значения по умолчанию можно указать в параметрах миксина
> 
> ![image](https://user-images.githubusercontent.com/43137324/98567463-613b9e00-22c9-11eb-930f-b974b702296b.png)

Исправил (3885dc9)

**Comment by Everrest1** [comment]
Отступы

![image](https://user-images.githubusercontent.com/43137324/98902841-e2fd1880-24cf-11eb-8f07-040e5365cffb.png)

**Comment by Everrest1** [comment]
Пробел

![image](https://user-images.githubusercontent.com/43137324/98903036-38392a00-24d0-11eb-8874-2afbaa9db2ff.png)

**Comment by n0sfer666** [comment]
> Отступы
> 
> ![image](https://user-images.githubusercontent.com/43137324/98902841-e2fd1880-24cf-11eb-8f07-040e5365cffb.png)



> Пробел
> 
> ![image](https://user-images.githubusercontent.com/43137324/98903036-38392a00-24d0-11eb-8874-2afbaa9db2ff.png)

Исправил (b334bbd)
