### ISSUE TITLE
JQuery

### ISSUE THREAD

**Issue by Everrest1** [n0sfer666/ui-kit__formElements#44]
Если используешь библиотеку, то используй её везде, а не вперемешку со стандартными методами

**Comment by n0sfer666** [comment]
Исправил там, где, на мой взгляд, нужно исправить. Остались еще смешанные классы, но там инъекции джиКвери используются для красоты кода, из-за методов типа show(), hide()
(67afb0c, b23c828)

**Comment by Everrest1** [comment]
Не, ты либо используешь методы jQuery вместо всех стандартных, либо не используешь jQuery. Давай так сделаем, хотя бы в рамках одного блока. Потому что это может быть очень неудобно и запутать, код же постоянно переписывается и ты, например, на одной строчке делаешь поиск по DOM querySelector, а на следующей find методом jQuery, и получается, что работаешь с разными интерфейсами

**Comment by n0sfer666** [comment]
На чистом js остался только range-slider, так как он не дружит с jQuery (3032f88, 8bfe5e8)
