### ISSUE TITLE
Переопределение стилей библиотек

### ISSUE THREAD

**Issue by Everrest1** [n0sfer666/ui-kit__formElements#46]
В идеале нужно задать свои классы, или в css указать блок как родительский селектор, чтобы твои стили не применялись глобально, а только в рамках данного блока, и делать это, соответственно, в самом блоке

**Comment by n0sfer666** [comment]
Сделал для item-quantity-dropdown (7820adc), paginationjs (9bf62ec), noUiSlider (8d9cfa0), slick-carousel (cdc4f75).
Осталось для air-datepicker, но мне кажется там без внесения изменений в код модуля никак, потому что календарь создаёт свой независимый блок в body 
![image](https://user-images.githubusercontent.com/21785370/94362829-9cda2a00-00c6-11eb-932e-ae42f04827cc.png)
