### ISSUE TITLE
Dropdown

### ISSUE THREAD

**Issue by Everrest1** [n0sfer666/ui-kit__formElements#47]
Библиотека внутренней реализацией обязывает использовать классы `iqdropdown`, `.iqdropdown-menu` и т.д. Но ты можешь добавить им и своё именование, и использовать его в своём коде.
`js-iqdropdown` и подобные выглядят странно

![image](https://user-images.githubusercontent.com/43137324/94396344-c6508f80-0172-11eb-89ea-e73a0fe46af7.png)

**Comment by Everrest1** [comment]
Эти правки остались без внимания

https://github.com/n0sfer666/FSD-Task-2/issues/39#issuecomment-699042846
https://github.com/n0sfer666/FSD-Task-2/issues/39#issuecomment-699043125
https://github.com/n0sfer666/FSD-Task-2/issues/39#issuecomment-699044058

**Comment by Everrest1** [comment]
Почему файлы со стилями находятся вне своих блоков?

![image](https://user-images.githubusercontent.com/43137324/94397403-cbaed980-0174-11eb-968b-1d375f72e4eb.png)

**Comment by n0sfer666** [comment]
> Почему файлы со стилями находятся вне своих блоков?
> 
> 
> 

Прошлый ревьювер [просил](https://github.com/n0sfer666/FSD-Task-2/issues/14#issue-606752488)

**Comment by n0sfer666** [comment]
> Библиотека внутренней реализацией обязывает использовать классы `iqdropdown`, `.iqdropdown-menu` и т.д. Но ты можешь добавить им и своё именование, и использовать его в своём коде.
> `js-iqdropdown` и подобные выглядят странно
> 
> ![image](https://user-images.githubusercontent.com/43137324/94396344-c6508f80-0172-11eb-89ea-e73a0fe46af7.png)

Отрефакторил (e17d9bb).
Остался только один кусок .iqdropdown-item-controls который создается библиотекой (пробовал продублировать по логике мой-класс+класс-библиотеки - всё равно создаётся).

**Comment by n0sfer666** [comment]
> Эти правки остались без внимания
> 
> [#39 (comment)](https://github.com/n0sfer666/FSD-Task-2/issues/39#issuecomment-699042846)
> [#39 (comment)](https://github.com/n0sfer666/FSD-Task-2/issues/39#issuecomment-699043125)
> [#39 (comment)](https://github.com/n0sfer666/FSD-Task-2/issues/39#issuecomment-699044058)

Сделал

**Comment by Everrest1** [comment]
Надо разобраться в чём проблема и найти решение. Может стоит не пересоздавать инстанс библиотеки, а просто обнулять эти значения?

![image](https://user-images.githubusercontent.com/43137324/94644864-72bd7d80-02fb-11eb-87c6-0c6917386358.png)

**Comment by n0sfer666** [comment]
> Надо разобраться в чём проблема и найти решение. Может стоит не пересоздавать инстанс библиотеки, а просто обнулять эти значения?
> 
Сделал (7d81780)

**Comment by Everrest1** [comment]
Массив results лишний здесь

![image](https://user-images.githubusercontent.com/43137324/95008741-9c451480-062d-11eb-9886-d82ee21d594f.png)

**Comment by Everrest1** [comment]
Можно тернарником это условие сделать

![image](https://user-images.githubusercontent.com/43137324/95008907-d2cf5f00-062e-11eb-8972-b5c74bc34eb0.png)

**Comment by Everrest1** [comment]
map возвращает массив

![image](https://user-images.githubusercontent.com/43137324/95009182-0dd29200-0631-11eb-8e91-b2e94296c454.png)

**Comment by Everrest1** [comment]
И тут тоже лучше этим воспользоваться, чтобы было меньше мутаций

![image](https://user-images.githubusercontent.com/43137324/95009224-63a73a00-0631-11eb-9908-e23824edcad9.png)

**Comment by n0sfer666** [comment]
> Массив results лишний здесь
> 
Исправил (e849c1e)




> Можно тернарником это условие сделать
> 
Исправил (150ac32)




> map возвращает массив
> 
> ![image](https://user-images.githubusercontent.com/43137324/95009182-0dd29200-0631-11eb-8e91-b2e94296c454.png)



> И тут тоже лучше этим воспользоваться, чтобы было меньше мутаций
> 
> ![image](https://user-images.githubusercontent.com/43137324/95009224-63a73a00-0631-11eb-9908-e23824edcad9.png)

Сделал вот так (19bfee0)
