### ISSUE TITLE
Неточности вёрстки

### ISSUE THREAD

**Issue by Everrest1** [n0sfer666/ui-kit__formElements#48]
При открытии dropdown изменяется высота
Правая часть со стрелкой кликабельна, но курсор не pointer

![Peek 2020-09-30 09-06](https://user-images.githubusercontent.com/43137324/94645172-3cccc900-02fc-11eb-9d77-ab9ee760b751.gif)

**Comment by Everrest1** [comment]
Нет стрелочек, как в макете

![image](https://user-images.githubusercontent.com/43137324/94645249-6e459480-02fc-11eb-9abc-7c3abc75398d.png)
![image](https://user-images.githubusercontent.com/43137324/94645339-a3ea7d80-02fc-11eb-94b5-83e394acaac4.png)

**Comment by Everrest1** [comment]
Странное выравнивание

![image](https://user-images.githubusercontent.com/43137324/94645380-c2e90f80-02fc-11eb-82e3-261ff66793fc.png)

**Comment by Everrest1** [comment]
Календарь выходит за границы сайдбара

![image](https://user-images.githubusercontent.com/43137324/94645552-28d59700-02fd-11eb-8ada-d69c42b6bd00.png)

**Comment by Everrest1** [comment]
Чёт dropdown'ы не соответствуют заголовкам

![image](https://user-images.githubusercontent.com/43137324/94645631-5de1e980-02fd-11eb-9bd3-708255fa1c71.png)

**Comment by n0sfer666** [comment]
> При открытии dropdown изменяется высота
> Правая часть со стрелкой кликабельна, но курсор не pointer
> 
Исправил (3770de3)

**Comment by n0sfer666** [comment]
> Нет стрелочек, как в макете
> 
> ![image](https://user-images.githubusercontent.com/43137324/94645249-6e459480-02fc-11eb-9abc-7c3abc75398d.png)
> ![image](https://user-images.githubusercontent.com/43137324/94645339-a3ea7d80-02fc-11eb-94b5-83e394acaac4.png)

Исправил (de2e89c)

**Comment by n0sfer666** [comment]
> Странное выравнивание
> 
> ![image](https://user-images.githubusercontent.com/43137324/94645380-c2e90f80-02fc-11eb-82e3-261ff66793fc.png)

Исправил (50ca158)

**Comment by n0sfer666** [comment]
> Календарь выходит за границы сайдбара
> 
Исправил (a40cf65)





> Чёт dropdown'ы не соответствуют заголовкам
> 
Исправил (cf05144)

**Comment by Everrest1** [comment]
Осталось

![image](https://user-images.githubusercontent.com/43137324/95009070-1b3b4c80-0630-11eb-9f84-ebc2cf6630ea.png)

**Comment by Everrest1** [comment]
В инпут можно ввести любое значение и нет никакого эффекта

Если ввода значений не будет, элемент интерактивный, курсор должен указывать на это

![image](https://user-images.githubusercontent.com/43137324/95009112-7705d580-0630-11eb-9ea1-228be85f44b5.png)

**Comment by n0sfer666** [comment]
> Осталось
> 
> ![image](https://user-images.githubusercontent.com/43137324/95009070-1b3b4c80-0630-11eb-9f84-ebc2cf6630ea.png)

это сделано специально, для PixelPerfect:
![image](https://user-images.githubusercontent.com/21785370/95075244-8e1ff280-0718-11eb-8d3e-9873f03ac408.png)

**Comment by n0sfer666** [comment]
> В инпут можно ввести любое значение и нет никакого эффекта
> 
> Если ввода значений не будет, элемент интерактивный, курсор должен указывать на это
> 
> ![image](https://user-images.githubusercontent.com/43137324/95009112-7705d580-0630-11eb-9ea1-228be85f44b5.png)

Исправил (eaba9bb)

**Comment by Everrest1** [comment]
Цвет инпута dropdown

![image](https://user-images.githubusercontent.com/43137324/95289809-bf193800-087c-11eb-8dcb-6a7a10076481.png)

**Comment by Everrest1** [comment]
Очистить и Применить редиректят на другую страницу

![image](https://user-images.githubusercontent.com/43137324/95290315-fd632700-087d-11eb-8996-314c3c6088c8.png)

**Comment by Everrest1** [comment]
Заголовок прилип к границе

![image](https://user-images.githubusercontent.com/43137324/95290457-57fc8300-087e-11eb-9f7a-65503066f147.png)

**Comment by n0sfer666** [comment]
> Цвет инпута dropdown
> 
Исправил (e1670fc)



> Очистить и Применить редиректят на другую страницу
> 
Исправил (d83f930)



> Заголовок прилип к границе
> 
Исправил (63817f4)

**Comment by Everrest1** [comment]
> это сделано специально, для PixelPerfect:
> ![image](https://user-images.githubusercontent.com/21785370/95075244-8e1ff280-0718-11eb-8d3e-9873f03ac408.png)

Если честно, выглядит как баг. Думаю, можно оставить верхний dropdown, а раскрытый вид сверять передвинув слой в плагине

**Comment by Everrest1** [comment]
![image](https://user-images.githubusercontent.com/43137324/95549429-52d33b80-0a18-11eb-8bcb-b6e5d464b3a1.png)

**Comment by n0sfer666** [comment]
> Если честно, выглядит как баг. Думаю, можно оставить верхний dropdown, а раскрытый вид сверять передвинув слой в плагине

Исправил (372b9e0)

**Comment by n0sfer666** [comment]
> ![image](https://user-images.githubusercontent.com/21785370/95560464-ff65eb00-0a21-11eb-8d7a-a5e0bd334c93.png)

Исправил (a3ceb94)

**Comment by Everrest1** [comment]
Линия перед футером

![image](https://user-images.githubusercontent.com/43137324/95610165-e9cbe200-0a70-11eb-882b-a7aa85113df7.png)

![image](https://user-images.githubusercontent.com/43137324/95610194-f6e8d100-0a70-11eb-9eb8-3aa1d918edee.png)

**Comment by Everrest1** [comment]
При наведении на инпут dropdown'а в открытом состоянии курсор становится обычным
На инпут календаря курсор pointer, но клик ничего не делает

![image](https://user-images.githubusercontent.com/43137324/95611139-7925c500-0a72-11eb-9822-597c6638a471.png)

**Comment by Everrest1** [comment]
Можно ввести любой тест, не ясно для чего
В макете нет эффекта на фокус инпута
Отступ календаря слишком большой

![image](https://user-images.githubusercontent.com/43137324/95611279-a8d4cd00-0a72-11eb-8792-91d77623ae57.png)

![image](https://user-images.githubusercontent.com/43137324/95611340-c144e780-0a72-11eb-9275-9f08d06e096d.png)

Цвет плейсхолдера не соответствует макету

![image](https://user-images.githubusercontent.com/43137324/95611884-80999e00-0a73-11eb-89bc-f5073426490f.png)

**Comment by Everrest1** [comment]
Ещё линия в футере

![image](https://user-images.githubusercontent.com/43137324/95611508-f8b39400-0a72-11eb-8844-cfe0c4dc4e1f.png)

![image](https://user-images.githubusercontent.com/43137324/95611520-ffdaa200-0a72-11eb-9acc-4e0d6e39ce04.png)

**Comment by n0sfer666** [comment]
> Линия перед футером

Сделал сначала неправильно (8667910), потом понял, что нужно полосу в футер добавить (be58853).

> При наведении на инпут dropdown'а в открытом состоянии курсор становится обычным
> На инпут календаря курсор pointer, но клик ничего не делает
> 

Курсор в дропдауне поправил (e3b71f2), на календаре клик работает + я сделал их readonly 





> Можно ввести любой тест, не ясно для чего
> В макете нет эффекта на фокус инпута
> Отступ календаря слишком большой
> 
> Цвет плейсхолдера не соответствует макету
> 

Поправил (66dd0c4, f89e6c3)





> Ещё линия в футере
> 

Исправил (be58853)

**Comment by Everrest1** [comment]
Цвет линии не соответствует макету

![image](https://user-images.githubusercontent.com/43137324/96346984-cf68b880-10af-11eb-9edc-e1e6c194aa71.png)

**Comment by Everrest1** [comment]
Отступ `люкс`

![image](https://user-images.githubusercontent.com/43137324/96347146-af85c480-10b0-11eb-902e-062ce483d66e.png)

**Comment by Everrest1** [comment]
Календарь странно перемещается

![Peek 2020-10-17 19-43](https://user-images.githubusercontent.com/43137324/96347177-07bcc680-10b1-11eb-9295-8cc4914c1192.gif)

**Comment by n0sfer666** [comment]
> Цвет линии не соответствует макету
> 
> ![image](https://user-images.githubusercontent.com/43137324/96346984-cf68b880-10af-11eb-9edc-e1e6c194aa71.png)

Сделано (37e6086)


> Отступ `люкс`
> 
> ![image](https://user-images.githubusercontent.com/43137324/96347146-af85c480-10b0-11eb-902e-062ce483d66e.png)

Вроде поправил (8fa5435)



> Календарь странно перемещается
> 
> ![Peek 2020-10-17 19-43](https://user-images.githubusercontent.com/43137324/96347177-07bcc680-10b1-11eb-9295-8cc4914c1192.gif)

Сделано (55276fb)
