### ISSUE TITLE
кодстайл

### ISSUE THREAD

**Issue by DaRkLoL1** [n0sfer666/ui-kit__formElements#5]
Для отступов нужно использовать пробелы, а не табы пример в webpack config

**Comment by n0sfer666** [comment]
done

**Comment by DaRkLoL1** [comment]
![Скриншот 18-04-2020 14_14_41](https://user-images.githubusercontent.com/32780725/79636243-fdac2080-817e-11ea-917c-4722fff9e655.png)
Стараться по максимуму избегать циклов и использовать встроенные методы массивов;
.map, .filter и тд обычно гораздо проще читаются, плюс функцию обработки одного элемента можно вынести и многократно использовать в разных местах.

**Comment by DaRkLoL1** [comment]
![Скриншот 18-04-2020 14_16_42](https://user-images.githubusercontent.com/32780725/79636293-4663d980-817f-11ea-88b0-59b2f8687c97.png)
Все теги идут только с классами - никаких пустых div, section и тд. Но можно для инлайновых элементов, если есть четкое понимание зачем. Это очень сильно мешает новым людям входить в проект и вам через некоторое время разобраться в собственной верстке;

**Comment by DaRkLoL1** [comment]
![Скриншот 25-04-2020 14_31_24](https://user-images.githubusercontent.com/32780725/80278751-80922580-8701-11ea-8a85-38f47a09c5c0.png)
лучше избегать сокращения index вместо i, и что за elem абстрактно дай лучше другое имя которое покажет что там лежит)  ${(i+1)} и используй пробелы

**Comment by DaRkLoL1** [comment]
![Скриншот 25-04-2020 14_31_24](https://user-images.githubusercontent.com/32780725/80278910-bdaae780-8702-11ea-9192-71be77b4b86e.png)
избегать циклы к js это тоже относится

**Comment by DaRkLoL1** [comment]
![Скриншот 11-05-2020 16_12_08](https://user-images.githubusercontent.com/32780725/81565572-39af5b80-93a2-11ea-9277-f805757248fc.png)
зачем тут переменная is888 и поставь пробелы между выражениями =>  index + 1,

**Comment by DaRkLoL1** [comment]
.apart_hrow  hrow что это значит

**Comment by DaRkLoL1** [comment]
isFrom2to4Reviews поставь вместо чисел слова

**Comment by DaRkLoL1** [comment]
![Скриншот 11-05-2020 16_30_55](https://user-images.githubusercontent.com/32780725/81567306-d07d1780-93a4-11ea-8b85-8de241958dda.png)
можешь расшифровать что ты тут делаешь

**Comment by DaRkLoL1** [comment]
![Скриншот 11-05-2020 16_43_04](https://user-images.githubusercontent.com/32780725/81568546-97de3d80-93a6-11ea-873d-6078d217c485.png)
лучше вместо тега использовать span и добавлять стиль в сss, потому что если будет нужно изменить жирность придется менять верстку, тем более b не носит никакой семантики

**Comment by DaRkLoL1** [comment]
![Скриншот 11-05-2020 16_47_09](https://user-images.githubusercontent.com/32780725/81568895-189d3980-93a7-11ea-938a-f93b8baf0109.png)
eslint пишет что это тут не нужно)

**Comment by DaRkLoL1** [comment]
![Скриншот 11-05-2020 16_48_50](https://user-images.githubusercontent.com/32780725/81569090-75005900-93a7-11ea-9a6b-4517e9aa6df4.png)
ты тут класс чтоль передаешь jsClass?

**Comment by n0sfer666** [comment]
> ![Скриншот 11-05-2020 16_12_08](https://user-images.githubusercontent.com/32780725/81565572-39af5b80-93a2-11ea-9277-f805757248fc.png)
> зачем тут переменная is888 и поставь пробелы между выражениями => index + 1,

Удалил... Сам уже не помню, зачем создавал :)

> .apart_hrow hrow что это значит

переименовал в .apart__horizontal-line


> isFrom2to4Reviews поставь вместо чисел слова

сделано


> ![Скриншот 11-05-2020 16_30_55](https://user-images.githubusercontent.com/32780725/81567306-d07d1780-93a4-11ea-8b85-8de241958dda.png)
> можешь расшифровать что ты тут делаешь

Это конструкция вставляет пробел после каждого кратного трём разряда числа не трогая при этом остальные символы (1000000 -> 1 000 000; 100000$ -> 100 000$; etc)
Пытался написать сам, но регулярные выражение пока слишком для меня сложны (даже сейчас не совсем понимаю, как это решение работает, перечитывал несколько раз главу про регулярки Крокфорда, но пока даётся со скрипом)
вынес с отдельную константу REGEXP_SPACE_SEPARATED_THOUSANDS.

**Comment by n0sfer666** [comment]
> > ![Скриншот 11-05-2020 16_12_08](https://user-images.githubusercontent.com/32780725/81565572-39af5b80-93a2-11ea-9277-f805757248fc.png)
> > зачем тут переменная is888 и поставь пробелы между выражениями => index + 1,
> 
> Удалил... Сам уже не помню, зачем создавал :)
> 
> > .apart_hrow hrow что это значит
> 
> переименовал в .apart__horizontal-line
> 
> > isFrom2to4Reviews поставь вместо чисел слова
> 
> сделано
> 
> > ![Скриншот 11-05-2020 16_30_55](https://user-images.githubusercontent.com/32780725/81567306-d07d1780-93a4-11ea-8b85-8de241958dda.png)
> > можешь расшифровать что ты тут делаешь
> 
> Это конструкция вставляет пробел после каждого кратного трём разряда числа не трогая при этом остальные символы (10000 -> 10 000; 1000$ -> 1 000$; etc)
Пытался написать сам, но регулярные выражение пока слишком для меня сложны (даже сейчас не совсем понимаю, как это решение работает, перечитывал несколько раз главу про регулярки Крокфорда, но даётся со скрипом)
> вынес с отдельную константу REGEXP_SPACE_AFTER_THREE_DIGITS.

**Comment by n0sfer666** [comment]
> ![Скриншот 11-05-2020 16_43_04](https://user-images.githubusercontent.com/32780725/81568546-97de3d80-93a6-11ea-873d-6078d217c485.png)
> лучше вместо тега использовать span и добавлять стиль в сss, потому что если будет нужно изменить жирность придется менять верстку, тем более b не носит никакой семантики

Сделал в компонентах apart и booking

> ![Скриншот 11-05-2020 16_47_09](https://user-images.githubusercontent.com/32780725/81568895-189d3980-93a7-11ea-938a-f93b8baf0109.png)
> eslint пишет что это тут не нужно)

в конфиге eslint добавил правило со значением:
"import/no-extraneous-dependencies": ["error", {"devDependencies": true}]

> ![Скриншот 11-05-2020 16_48_50](https://user-images.githubusercontent.com/32780725/81569090-75005900-93a7-11ea-9a6b-4517e9aa6df4.png)
> ты тут класс чтоль передаешь jsClass?

Убрал.
+ изменю инициализацию, но это уже другой issue

**Comment by Everrest1** [comment]
Есть причина использовать по два равнозначных селектора?
![image](https://user-images.githubusercontent.com/43137324/84465816-086bc900-ac89-11ea-8cc5-5e2794177b26.png)
![image](https://user-images.githubusercontent.com/43137324/84465743-de1a0b80-ac88-11ea-8bcb-df9c852709c6.png)

**Comment by Everrest1** [comment]
Приведи к единой логике пустые строки в scss. Между свойствами они не нужны. @include не стоит размещать прямо между свойствами, сделай как-то обособленно, в самом конце, например. Также оставляй пропускай строку перед селектором. 
Можешь, кстати, поставить prettier, он это за тебя будет делать) Это не строгий свод правил, самое главное - чтобы было однообразно во всём проекте.
![image](https://user-images.githubusercontent.com/43137324/84466179-dad34f80-ac89-11ea-9558-cf169f68c9f3.png)

**Comment by n0sfer666** [comment]
> Есть причина использовать по два равнозначных селектора?
> ![image](https://user-images.githubusercontent.com/43137324/84465816-086bc900-ac89-11ea-8cc5-5e2794177b26.png)
> ![image](https://user-images.githubusercontent.com/43137324/84465743-de1a0b80-ac88-11ea-8bcb-df9c852709c6.png)

Таких причин нет. Исправил (e394cc1)

**Comment by n0sfer666** [comment]
> Приведи к единой логике пустые строки в scss. Между свойствами они не нужны. @include не стоит размещать прямо между свойствами, сделай как-то обособленно, в самом конце, например. Также оставляй пропускай строку перед селектором.
> Можешь, кстати, поставить prettier, он это за тебя будет делать) Это не строгий свод правил, самое главное - чтобы было однообразно во всём проекте.
> ![image](https://user-images.githubusercontent.com/43137324/84466179-dad34f80-ac89-11ea-9558-cf169f68c9f3.png)

Привёл всё к единому стилю (6d806b1)

**Comment by Everrest1** [comment]
Здесь тоже не нужно использовать шаблонные строки

![image](https://user-images.githubusercontent.com/43137324/86089909-30955d80-baba-11ea-98f4-ec165efb93ab.png)

**Comment by n0sfer666** [comment]
> Здесь тоже не нужно использовать шаблонные строки
> 
> ![image](https://user-images.githubusercontent.com/43137324/86089909-30955d80-baba-11ea-98f4-ec165efb93ab.png)

Исправил + просмотрел по всему проекту использование `${}` (9485543)

**Comment by Everrest1** [comment]
Можно закрыть

**Comment by n0sfer666** [comment]
yes, sir
