### ISSUE TITLE
Переменные jQuery

### ISSUE THREAD

**Issue by Everrest1** [n0sfer666/ui-kit__formElements#50]
Все переменные, которые поддерживают jQuery API, должны начинаться со знака `$` 

https://github.com/fullstack-development/front-end-best-practices/blob/master/JS/README.md#5.3

![image](https://user-images.githubusercontent.com/43137324/96545057-bd0d9b00-12b8-11eb-82ca-9e019a6cb0f5.png)
![image](https://user-images.githubusercontent.com/43137324/96545156-e29aa480-12b8-11eb-82f9-34c09b2c4e68.png)

**Comment by n0sfer666** [comment]
> Все переменные, которые поддерживают jQuery API, должны начинаться со знака `$`
> 
> https://github.com/fullstack-development/front-end-best-practices/blob/master/JS/README.md#5.3
> 
> ![image](https://user-images.githubusercontent.com/43137324/96545057-bd0d9b00-12b8-11eb-82ca-9e019a6cb0f5.png)
> ![image](https://user-images.githubusercontent.com/43137324/96545156-e29aa480-12b8-11eb-82f9-34c09b2c4e68.png)

Исправил (1db8c0f) + прошёлся по всему проекту.

**Comment by Everrest1** [comment]
`container` тут тоже jq элемент

![image](https://user-images.githubusercontent.com/43137324/97395443-662e4400-18fe-11eb-9421-a7c2276f1678.png)

**Comment by Everrest1** [comment]
element

![image](https://user-images.githubusercontent.com/43137324/97395590-b7d6ce80-18fe-11eb-9b1e-33aa4c881e08.png)

**Comment by n0sfer666** [comment]
Переименовал container, ratesElements и element (связанных с перебором ratesElements) (8a8b511)
