### ISSUE TITLE
Использование методов массивов

### ISSUE THREAD

**Issue by Everrest1** [n0sfer666/ui-kit__formElements#51]
Нерациональное использование метода map. Если искомый элемент будет первым, цикл не завершится и продолжит идти по оставшимся элементам впустую
Очень странное использование целого массива для получения всего 1 переменной, судя по возвращаемому результату

![image](https://user-images.githubusercontent.com/43137324/96545606-c2b7b080-12b9-11eb-8a19-fd647785cd76.png)

**Comment by Everrest1** [comment]
А почему бы сразу не использовать `reduce`

![image](https://user-images.githubusercontent.com/43137324/96548133-5d19f300-12be-11eb-946f-c3c9b1f60ef4.png)

**Comment by n0sfer666** [comment]
> Нерациональное использование метода map. Если искомый элемент будет первым, цикл не завершится и продолжит идти по оставшимся элементам впустую
> Очень странное использование целого массива для получения всего 1 переменной, судя по возвращаемому результату
> 
> ![image](https://user-images.githubusercontent.com/43137324/96545606-c2b7b080-12b9-11eb-8a19-fd647785cd76.png)

Заменил map на find (439b4ed)

**Comment by n0sfer666** [comment]
> А почему бы сразу не использовать `reduce`
> 
> ![image](https://user-images.githubusercontent.com/43137324/96548133-5d19f300-12be-11eb-946f-c3c9b1f60ef4.png)

Не получится. Нужно сначала собрать массив outerStrings, а только потом "суммировать" в одну строку... или я просто не могу найти решения =\

**Comment by Everrest1** [comment]
> Не получится. Нужно сначала собрать массив outerStrings, а только потом "суммировать" в одну строку... или я просто не могу найти решения =\

Вместо map сразу reduce используешь и всё, просто в зависимости от условия возвращаешь измененный аккумулятор, либо нет
