### ISSUE TITLE
Повторение класса

### ISSUE THREAD

**Issue by Everrest1** [n0sfer666/ui-kit__formElements#52]
Можно же сохранить в переменной только класс модификатора

![image](https://user-images.githubusercontent.com/43137324/96545972-7a4cc280-12ba-11eb-9c4b-383f4cce3e79.png)

**Comment by Everrest1** [comment]
Нет необходимости так усложнять

![image](https://user-images.githubusercontent.com/43137324/96546096-ae27e800-12ba-11eb-8ca2-feefbbc31df9.png)

**Comment by n0sfer666** [comment]
> Можно же сохранить в переменной только класс модификатора
> 
> ![image](https://user-images.githubusercontent.com/43137324/96545972-7a4cc280-12ba-11eb-9c4b-383f4cce3e79.png)

Исправил (005f72a)

> Нет необходимости так усложнять
> 
> ![image](https://user-images.githubusercontent.com/43137324/96546096-ae27e800-12ba-11eb-8ca2-feefbbc31df9.png)

Исправил (bd5278c)
