### ISSUE TITLE
Валидность html

### ISSUE THREAD

**Issue by romansilivestrov** [n0sfer666/ui-kit__formElements#61]
Страницы не проходят [валидацию](https://validator.w3.org/nu/?doc=https%3A%2F%2Fn0sfer666.github.io%2FFSD-Task-2%2Flanding-page.html).

**Comment by n0sfer666** [comment]
Всё исправил. На некоторых страницах остались вот такие штуки:
![image](https://user-images.githubusercontent.com/21785370/144222594-f4501ea7-01e8-49b5-a5bc-df90d19f4b1d.png)
