### ISSUE TITLE
Ссылки между страницами

### ISSUE THREAD

**Issue by romansilivestrov** [n0sfer666/ui-kit__formElements#63]
Ссылки переходов между страницами (вход, регистрация, лэндинг) не ведут на соответствующие страницы.

**Comment by n0sfer666** [comment]
В #61 исправил вместе со всеми остальными невалидными ссылками

**Comment by romansilivestrov** [comment]
Ещё следует добавить в карточки номеров ссылки для перехода на страницу комнаты:
![image](https://user-images.githubusercontent.com/85496220/144999841-170121c4-1680-4aac-a775-ebc8fc5af0fb.png)

Несуществующие же ссылки лучше сделать очевидными заглушками по типу [//mock-url](//mock-url) или [//replace-me](//replace-me).

**Comment by n0sfer666** [comment]
Добавил в параметре миксина link, карточка теперь ссылка (кроме кнопок перелистывания и rate). Отредактировал сопутствующие файлы чтобы всё работало.
