### ISSUE TITLE
Типы текстовых инпутов

### ISSUE THREAD

**Issue by romansilivestrov** [n0sfer666/ui-kit__formElements#64]
Желательно добавить в миксин праметр для типа инпута. Помимо типа `text` в проекте встречаются как минимум `email` и `password` (с паролями особенно заметно).

**Comment by n0sfer666** [comment]
забавно, я это сделал, уже давно, только в миксин добавить забыл и оно не работало =\

**Comment by romansilivestrov** [comment]
<s>Поля паролей в формах не поменялись. Пароль должен отображаться точками:</s>
![image](https://user-images.githubusercontent.com/85496220/144995657-3d3b1067-3467-4d23-b32d-5766367a3ae2.png)

<s>И значения атрибутов принято писать строчными буквами (`type="email"` вместо `type="Email"`).</s> 

На github pages, похоже, не самая новая версия.
