### ISSUE TITLE
Форма подписки

### ISSUE THREAD

**Issue by romansilivestrov** [n0sfer666/ui-kit__formElements#65]
Поле подписки не относится к какой-либо форме. Соответственно, отправка невозможна. Также значения атрибутов в html принято писать с маленькой буквы (`type`).

**Comment by n0sfer666** [comment]
Если всё правильно понял, то готово. В значении атрибутов с прописной буквы есть исключение - placeholder.

**Comment by romansilivestrov** [comment]
![image](https://user-images.githubusercontent.com/85496220/144997024-50349bb5-64fa-4d9b-8044-fadc1d393f4e.png)
