### ISSUE TITLE
Модификаторы БЭМ

### ISSUE THREAD

**Issue by romansilivestrov** [n0sfer666/ui-kit__formElements#67]
На примере `button`: есть 4 стиля `'textual', 'gradient', 'border', 'submitting'`. Соответственно, у данных модификаторов должен быть ключ. Вместо `button_textual`, `button_gradient` и т.д. должно быть `button_style_textual`, `button_style_gradient` etc.

**Comment by n0sfer666** [comment]
done. Список "попавших под раздачу" получился большой. Надеюсь, я не перестарался :)
