### ISSUE TITLE
Параметры pug миксинов по умолчанию

### ISSUE THREAD

**Issue by romansilivestrov** [n0sfer666/ui-kit__formElements#69]
Встречаются pug-миксины с большим количеством параметров, которые не помещаются в один экран (например, `footer`, `header`). Такие параметры для читаемости следует выносить.

**Comment by n0sfer666** [comment]
сделал в таком стиле:
```js
mixin amenity(options = {})
  -
    const {
      icon = 'tag_faces',
      title = 'Title',
      description = 'Description',
      withLine = true,
    } = options;
```
