### ISSUE TITLE
Семантика html

### ISSUE THREAD

**Issue by romansilivestrov** [n0sfer666/ui-kit__formElements#70]
Предполагается, что тэг `main` содержит главный контент страницы, а сейчас он просто обёртка для всей страницы. Правильнее будет вынести `header`, `main` и `footer` на один уровень.

Тэг `article` используется для позиционирования форм, для чего лучше подойдёт обычный `div`. А `article` лучше подойдёт для комментариев, например.

Expandable checkbox list стоит сделать списком (`ul`):
![image](https://user-images.githubusercontent.com/85496220/145543022-eef1de39-2c0a-42de-82db-d77346fa2aae.png)

Элементы навигации обычно оборачивают в тэг `nav`:
![image](https://user-images.githubusercontent.com/85496220/145542859-d70935da-d23a-4c8c-9c01-d70715875b04.png)
![image](https://user-images.githubusercontent.com/85496220/145543095-306fa65b-1269-4660-ab35-b34ae02623f3.png)

**Comment by n0sfer666** [comment]
Всё исправил. Обернул ещё checkbox, тегом li.

**Comment by romansilivestrov** [comment]
А если сам чекбокс обернуть в `li`, то вне списка можно его использовать?

**Comment by romansilivestrov** [comment]
У чекбоксов появились маркеры:
![image](https://user-images.githubusercontent.com/85496220/145986175-5d3d0bae-72c6-4eb5-9ef5-cedc5884d20a.png)

**Comment by n0sfer666** [comment]
> А если сам чекбокс обернуть в `li`, то вне списка можно его использовать?

`The <li> HTML element is used to represent an item in a list. It must be contained in a parent element: an ordered list (<ol>), an unordered list (<ul>), or a menu (<menu>).`
Определенно нет :( Исправлю
