### ISSUE TITLE
Perfect pixel

### ISSUE THREAD

**Issue by romansilivestrov** [n0sfer666/ui-kit__formElements#73]
Есть расхождения с макетом:

![image](https://user-images.githubusercontent.com/85496220/145989604-b189596e-17be-4407-9eba-cc3f1f00c9e2.png)

![image](https://user-images.githubusercontent.com/85496220/145989688-579eec1c-fd93-4fb1-a2f3-a545a09a35ee.png)

![image](https://user-images.githubusercontent.com/85496220/145990086-b9a14bf4-1f3f-419a-89ba-fcb483d59553.png)

![image](https://user-images.githubusercontent.com/85496220/145990275-db2f4fb0-e083-4198-8064-752e3910ee4f.png)

![image](https://user-images.githubusercontent.com/85496220/145990414-72e69810-b6a5-4185-a03d-1fa89e76ffca.png)

**Comment by n0sfer666** [comment]
сделал все страницы сайта + colors & type

**Comment by n0sfer666** [comment]
закончил
