### ISSUE TITLE
Неактуальный код

### ISSUE THREAD

**Issue by romansilivestrov** [n0sfer666/ui-kit__formElements#76]
Неактуальный код не комментируем, а [удаляем](https://github.com/fullstack-development/front-end-best-practices/blob/master/JS/README.md#1.23):
![image](https://user-images.githubusercontent.com/85496220/146955403-bcf75afb-4b51-4d65-841d-5d09e5d71ddf.png)

**Comment by n0sfer666** [comment]
done

**Comment by romansilivestrov** [comment]
![image](https://user-images.githubusercontent.com/85496220/147260976-e8f1cb25-b4c7-4175-8669-636ac9dfbc3d.png)
