### ISSUE TITLE
семантика

### ISSUE THREAD

**Issue by sodiqit** [n0sfer666/ui-kit__formElements#78]
три h2 подряд уже перебор)  тут одного спокойно хватит
![image](https://user-images.githubusercontent.com/47000555/152297503-ab3fbaff-1659-4b35-9726-18002ba22136.png)

**Comment by sodiqit** [comment]
для коммента хорошо подойдет тег `article`
![image](https://user-images.githubusercontent.com/47000555/152297902-89630c39-ce78-4dc0-bf7f-d30c12c63dec.png)

**Comment by sodiqit** [comment]
забыл `li` добавить
![image](https://user-images.githubusercontent.com/47000555/152298491-f38a25cf-ab05-42c9-bb87-c381fbaa68b7.png)

**Comment by n0sfer666** [comment]
[f1c27c4](https://github.com/n0sfer666/FSD-Task-2/commit/f1c27c451dcc066c17ddb8876de60f099440932d) промахнулся по клавиатуре 😥

**Comment by n0sfer666** [comment]
> три h2 подряд уже перебор) тут одного спокойно хватит 

Надеюсь, имелось ввиду это [f1c27c4](https://github.com/n0sfer666/FSD-Task-2/commit/f1c27c451dcc066c17ddb8876de60f099440932d)

**Comment by n0sfer666** [comment]
> для коммента хорошо подойдет тег `article`

В этом компоненте с таким тегом был сам текст отзыва.
Сделал текст тегом `p`, а компоненту тегом `article`  [6c2fe3d](https://github.com/n0sfer666/FSD-Task-2/commit/6c2fe3dd100cdf21ae6d7a34416450f19e17fd36)

**Comment by n0sfer666** [comment]
> забыл `li` добавить

Добавил.
Также сбросил list-style-type глобально для всех ul [c8d883a](https://github.com/n0sfer666/FSD-Task-2/commit/c8d883a802b8d7326ef1927d72523a500ef86b9a)
