### ISSUE TITLE
Eslint

### ISSUE THREAD

**Issue by sodiqit** [n0sfer666/ui-kit__formElements#79]
Добавь скрипт для запуска eslint, прогони его и поправь ошибки. Пока попалась вот эта
![image](https://user-images.githubusercontent.com/47000555/152298084-ca84525b-05a1-4d7a-944e-f317e7731d7f.png)

**Comment by n0sfer666** [comment]
Добавил 3 скрипта для линта:
>     "lint": "eslint --quiet src/**/*.js",  
>     "lint:full": "eslint src/**/*.js",  
>     "lint:fix": "eslint --quiet --fix src/**/*.js"  

Исправил 6 ошибок [b0808ae](https://github.com/n0sfer666/FSD-Task-2/commit/b0808ae3c872ef35df02040225a950117bd8feda)
