### ISSUE TITLE
DropDown

### ISSUE THREAD

**Issue by DaRkLoL1** [n0sfer666/ui-kit__formElements#8]
У тебя щас не работает кнопка очистки и после гостей ставится точка с запятой. Нужно поправить)
![Скриншот 31-03-2020 13_21_19](https://user-images.githubusercontent.com/32780725/78015828-9efb4000-7352-11ea-99a9-570662d2caeb.png)

**Comment by n0sfer666** [comment]
done.

**Comment by DaRkLoL1** [comment]
![ntqnnHuic3](https://user-images.githubusercontent.com/32780725/79635856-2b439a80-817c-11ea-8b08-8acb7880637b.gif)
Почему то при клике в эту область дропдаун закрывается

**Comment by DaRkLoL1** [comment]
![Скриншот 18-04-2020 14_01_47](https://user-images.githubusercontent.com/32780725/79635982-30551980-817d-11ea-9fce-f8dd91295b67.png)
А где тут стрелочка вниз?)

**Comment by DaRkLoL1** [comment]
![Скриншот 25-04-2020 14_59_11](https://user-images.githubusercontent.com/32780725/80279320-8853c900-8705-11ea-969b-a90a6fb10404.png)

запятая перед 1
