### ISSUE TITLE
БЕМ

### ISSUE THREAD

**Issue by DaRkLoL1** [n0sfer666/ui-kit__formElements#9]
Используй для разделения блока и элемента 2 нижних подчеркивания, а для модификаторов 1 нижнее подчеркивание. Например блок__элемент_имя-модификатора_значение-модификатора.

Не используй задание стилей по тегам, используй только классы.
![Скриншот 31-03-2020 13_28_17](https://user-images.githubusercontent.com/32780725/78016932-2b5a3280-7354-11ea-9f38-a6e56dbc7ccf.png)

**Comment by n0sfer666** [comment]
done.

**Comment by DaRkLoL1** [comment]
![Скриншот 18-04-2020 13_40_32](https://user-images.githubusercontent.com/32780725/79635679-ecf9ab80-817a-11ea-95d0-c5af973d46b1.png)
У нас запрещены примеси https://github.com/fullstack-development/front-end-best-practices/blob/master/CSS/bem.md 5 пункт

**Comment by DaRkLoL1** [comment]
![Скриншот 25-04-2020 14_25_17](https://user-images.githubusercontent.com/32780725/80278627-a4a13700-8700-11ea-89ff-b9692259d867.png)
миксы тоже запрещены)

**Comment by Everrest1** [comment]
Тут ещё селектор по тегу

![image](https://user-images.githubusercontent.com/43137324/84467042-f2133c80-ac8b-11ea-98f1-d80077294671.png)

**Comment by Everrest1** [comment]
Миксы 

![image](https://user-images.githubusercontent.com/43137324/84467252-9b5a3280-ac8c-11ea-947f-e78782fd4508.png)

**Comment by Everrest1** [comment]
Сейчас много где используются элементы вне своего блока, что запрещено методологией. Посмотри по всему проекту, плиз.

![image](https://user-images.githubusercontent.com/43137324/84467346-ec6a2680-ac8c-11ea-9eaf-3336b6cac6c0.png)

**Comment by Everrest1** [comment]
Модификатор - всегда прилагательное или фраза с прилагательным. 
п.1. https://github.com/fullstack-development/front-end-best-practices/blob/master/CSS/bem.md

![image](https://user-images.githubusercontent.com/43137324/84467499-70241300-ac8d-11ea-93b5-70304e4ce6c5.png)
![image](https://user-images.githubusercontent.com/43137324/84467539-8e8a0e80-ac8d-11ea-8094-ae1c690d72fc.png)

**Comment by Everrest1** [comment]
Блок, элемент — всегда имя существительное п.1. https://github.com/fullstack-development/front-end-best-practices/blob/master/CSS/bem.md

![image](https://user-images.githubusercontent.com/43137324/84467778-2851bb80-ac8e-11ea-81e6-ab04df47f83d.png)

**Comment by Everrest1** [comment]
Блок в блоке

![image](https://user-images.githubusercontent.com/43137324/84468726-94352380-ac90-11ea-9910-6e85b70ee94f.png)

**Comment by n0sfer666** [comment]
> Тут ещё селектор по тегу
> 
> ![image](https://user-images.githubusercontent.com/43137324/84467042-f2133c80-ac8b-11ea-98f1-d80077294671.png)

исправил в другом ишью (6d806b1)

**Comment by n0sfer666** [comment]
> Миксы
> 
> ![image](https://user-images.githubusercontent.com/43137324/84467252-9b5a3280-ac8c-11ea-947f-e78782fd4508.png)

Исправил. Прошёл по всему проекту - миксов не нашел, но избавился заодно от div(class="class"), сделав .class (6e0b50e)

**Comment by n0sfer666** [comment]
> Блок в блоке
> 
> ![image](https://user-images.githubusercontent.com/43137324/84468726-94352380-ac90-11ea-9910-6e85b70ee94f.png)

Имена селекторов и структура html продиктованы внешним модулем [item-quantity-dropdown](https://www.npmjs.com/package/item-quantity-dropdown)

**Comment by n0sfer666** [comment]
> Сейчас много где используются элементы вне своего блока, что запрещено методологией. Посмотри по всему проекту, плиз.
> 
> ![image](https://user-images.githubusercontent.com/43137324/84467346-ec6a2680-ac8c-11ea-9eaf-3336b6cac6c0.png)




> Модификатор - всегда прилагательное или фраза с прилагательным.
> п.1. https://github.com/fullstack-development/front-end-best-practices/blob/master/CSS/bem.md
> 
> ![image](https://user-images.githubusercontent.com/43137324/84467499-70241300-ac8d-11ea-93b5-70304e4ce6c5.png)
> ![image](https://user-images.githubusercontent.com/43137324/84467539-8e8a0e80-ac8d-11ea-8094-ae1c690d72fc.png)



> Блок, элемент — всегда имя существительное п.1. https://github.com/fullstack-development/front-end-best-practices/blob/master/CSS/bem.md
> 
> ![image](https://user-images.githubusercontent.com/43137324/84467778-2851bb80-ac8e-11ea-81e6-ab04df47f83d.png)

Прошелся по всему проекту - исправил, где нашел + поправил код-стиль (issue #5)

**Comment by Everrest1** [comment]
Много где сейчас используются классы модификаторов без класса блока/элемента

![image](https://user-images.githubusercontent.com/43137324/86431507-059f4980-bd06-11ea-881f-fab566412b4d.png)
![image](https://user-images.githubusercontent.com/43137324/86431525-12bc3880-bd06-11ea-89ed-3442c85eb9ec.png)

**Comment by n0sfer666** [comment]
> Много где сейчас используются классы модификаторов без класса блока/элемента
> 
> ![image](https://user-images.githubusercontent.com/43137324/86431507-059f4980-bd06-11ea-881f-fab566412b4d.png)
> ![image](https://user-images.githubusercontent.com/43137324/86431525-12bc3880-bd06-11ea-89ed-3442c85eb9ec.png)

Исправил (3349de8, ab6fc84, b84f4a4)

**Comment by Everrest1** [comment]
Можно закрыть

**Comment by n0sfer666** [comment]
yes, sir
